### ISSUE TITLE
Null reference in ApplyParamsXmlToActionParameters

### ISSUE THREAD

**Issue by anushprabhu** [domaindrivendev/Swashbuckle.AspNetCore#1055]
Am attempting to upgrade our swagger nuget package to 4.0.1 and running into System.NullReferenceException : Object reference not set to an instance of an object.

My current understanding is it happens due to incomplete parameter for actions but the package should be able to handle and not throw null reference.

Here is the stack:
```
at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.<>c__DisplayClass10_0.<ApplyParamsXmlToActionParameters>b__0(ParameterDescriptor p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.ApplyParamsXmlToActionParameters(IList`1 parameters, XPathNavigator methodNode, ApiDescription apiDescription)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.Apply(Operation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItems(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by sarajang** [comment]
I am in the same boat. Trying to upgrade from v3 to v4.

**Comment by anushprabhu** [comment]
Thanks to my colleague Santhosh Rajangam for sharing this work around! I was able to work around this failure by moving the `swaggerOptions.IncludeXmlComments(<filename>)` right after `swaggerOptions.SwaggerDoc()`. Looks like there is some ordering requirement with new version.
