### ISSUE TITLE
5.0.0-rc2 with asp.net core 3.0 preview3 error

### ISSUE THREAD

**Issue by Dolphinsimon** [domaindrivendev/Swashbuckle.AspNetCore#1105]
Just a small project with 5.0.0-rc2 and asp .netcore 3.0 p3, the application will get an exception when visiting the swagger page. 

`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Memory`1.Slice(Int32 start, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetChunkedMemory(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.GetSpan(Int32 sizeHint)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteMultiSegmentEncoded(PipeWriter writer, String text, Encoding encoding, Span`1 destination, Int32 encodedLength)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.RespondWithIndexHtml(HttpResponse response)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.`

Is there anything I've missed?
![QQ截图20190331222222](https://user-images.githubusercontent.com/4425053/55290260-b46a2100-5403-11e9-9f69-a1926b30d860.png)

**Comment by Dolphinsimon** [comment]
The same project with 5.0.0-rc2 and asp.net core 2.2 doesn't have this problem.

**Comment by domaindrivendev** [comment]
I believe this is due to a Kestrel bug introduced with ASP.NET Core 3.0.

It's being tracked here - https://github.com/aspnet/AspNetCore/issues/8815

Also, see here for the Swashbuckle specific discussion - https://github.com/aspnet/AspNetCore/issues/8815

**Comment by Dolphinsimon** [comment]
With new 3.0 P4 SDK, this error has been solved.

**Comment by domaindrivendev** [comment]
Closing as it appears to have been an upstream (AspNetCore) issue that has been fixed with the latest preview
