### ISSUE TITLE
NullReferenceException when upgrading to v5.0 rc2

### ISSUE THREAD

**Issue by moakley7842** [domaindrivendev/Swashbuckle.AspNetCore#1131]
In trying to take advantage of my response type oneOf in OpenAPI 3 we are verifying support in V5 rc2.  So we upgraded packages to Swashbuckle.AspNetCore.* v5.0 rc2 packages which comes with a dependency on Microsoft.OpenAPI v1.1.2. 

The change made to the source was limited to:

```csharp
using Microsoft.OpenApi.Models;

services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "IdP Admin API", Version = "v1" });
    c.DescribeAllEnumsAsStrings();
});
```

The following did not change when upgrading to rc2

```csharp
app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("../swagger/v1/swagger.json", "IdP Admin API");
});
```

Trying to display the swaggerUI I change my base Uri after starting to http:\localhost:15084\swagger This is now returning a 500. When I check the output I see a null reference exception (See below). My question is what addition setup do I need to successfully produce and display the json file?

```text
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HLM36LN4REMD", Request id "0HLM36LN4REMD:00000002": An unhandled exception was thrown by the application.

System.NullReferenceException: Object reference not set to an instance of an object.
at System.Object.GetType()
at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.TryCreateFor(OpenApiSchema schema, Object value, IOpenApiAny& openApiAny)
at Swashbuckle.AspNetCore.SwaggerGen.ObjectSchemaGenerator.GeneratePropertySchema(JsonProperty jsonProperty, Object[] attributes, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.ObjectSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.ReferencedSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestMediaType(String contentType, ApiDescription apiDescription, SchemaRepository schemaRepository)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable1 source, Func2 keySelector, Func2 elementSelector, IEqualityComparer1 comparer)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, IEnumerable1 methodAttributes, SchemaRepository schemaRepository) at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository) at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable1 apiDescriptions, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable1 apiDescriptions, SchemaRepository schemaRepository) at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__5.MoveNext()
```

**Comment by domaindrivendev** [comment]
To support Swagger/OAI V3, there was a significant refactor to the generation components. I guess this is an "edge-case" regression that's crept in with those changes.

But, from the info you've provided, it's difficult for me to understand what circumstances cause the issue. It would be very helpful if you could pull down the source and debug through it to understand why the null ref is occurring. Once the root cause has been identified, the fix should be relatively straightforward.

**Comment by moakley7842** [comment]
Closed.  We will be modifying our API.

**Comment by schrufygroovy** [comment]
same problem
