### ISSUE TITLE
I have an exception if generate V2 version

### ISSUE THREAD

**Issue by IvanovNiko** [domaindrivendev/Swashbuckle.AspNetCore#1184]
I have an exception when trying to generate V2 format of swagger specification:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.OpenApi.Models.OpenApiDocument.WriteHostInfoV2(IOpenApiWriter writer, IList`1 servers)
   at Microsoft.OpenApi.Models.OpenApiDocument.SerializeAsV2(IOpenApiWriter writer)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

My settings:
            "DocumentName": "v1",
            "RouteTemplate": "/api-docs/{documentName}/swagger.json"

**Comment by IvanovNiko** [comment]
It is actual when my web api uses basepath. For example my web api hosted at http://example.com:8111/someservice.
When i am trying to get swagger.json as http://example.com:8111/someservice/swagger/v1/swagger.json i have an exception described above.

**Comment by sazonovm** [comment]
hi!

did it resolved?

**Comment by sazonovm** [comment]
it was a base path problem

**Comment by cgreenza** [comment]
I get this `UriFormatException` when doing a `UsePathBase` (as described in #1253) together with `SerializeAsV2 = true` in `UseSwagger` (this is with version 5 of Swashbuckle.AspNetCore)

It looks like `OpenApiDocument` is not able to serialize an `OpenApiServer.Url` that contains only the path portion for V2 (but it works for V3). For V2 the serializer should probably map such URLs directly to [`basePath`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swaggerBasePath) with an empty `host` field.

**Comment by domaindrivendev** [comment]
Dup of #1495
