### ISSUE TITLE
"System.InvalidOperationException: TODO:" (Not a JArray issue?)

### ISSUE THREAD

**Issue by HughPH** [domaindrivendev/Swashbuckle.AspNetCore#1202]
Version 5.0.0-rc2

I have some big complex objects. It's not clear to me what SwashBuckle was doing at the time. Maybe a good first step would be to make the exception more clear, to help all of us?

I'm making an assumption that this is not a JArray issue because as far as I know, I'm not using Newtonsoft anywhere in this project. However, I tried NSwag and that's given me an error saying it can't load file or assembly Microsoft.AspNetCore.Mvc.NewtonsoftJson.

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/swagger/v1/swagger.json  
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: TODO:
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ArraySchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ObjectSchemaGenerator.GeneratePropertySchema(JsonProperty jsonProperty, Object[] attributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ObjectSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ReferencedSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(Type type, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass19_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(String statusCode, ApiResponseType apiResponseType, IEnumerable`1 methodAttributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, IEnumerable`1 methodAttributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by HughPH** [comment]
is this in a publicly consumable version?

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/6f9e899cfe46e8d99a12e42e378e7c03693dd1c2

**Comment by Jabolcnik** [comment]
Same issue here

**Comment by HughPH** [comment]
@Jabolcnik if you grab the source, add it to your own solution and build it, you'll be able to figure out what's killing it. My issue turned out to be a circular reference (home-grown linked list), although that wouldn't actually be exposed via the API in real usage because I have a custom serialiser & deserialiser to deal with it. I've left this open to hopefully get some more attention on the fact that the messages need to be clearer. The fix in [6f9e899](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/6f9e899cfe46e8d99a12e42e378e7c03693dd1c2) is not yet in a publicly consumable version, and it only goes a little way to making errors meaningful. There should be some loop detection IMO, some of us have to put APIs in front of other peoples' junk without necessarily becoming intimately familiar with it.

**Comment by domaindrivendev** [comment]
@HughPH self-referencing types should be fully supported and so loop detection should not be necessary. So, I'd be very interested to learn more about your circular-dependency problem. Perhaps you could post a minimal set of repro steps?

It's also worth noting that the latest code now applies a `FallbackHandler` that generates a simple `string` schema for any types that it simply doesn't now how to describe. Keep in mind that Swashbuckle inspects static code constructs (it does not execute any of your code) and therefore there will always be some cases where it's literally not possible to pick up certain serialization behaviors (particularly those of the imperative nature). Rather than throw an exception in these cases, I've decided to just provide a fallback.

**Comment by HughPH** [comment]
@domaindrivendev I shall take a branch and remove stuff until I have a minimal failing codebase, then rename some stuff to protect the innocent.

On Monday.

**Comment by Jabolcnik** [comment]
@HughPH  - thank you for suggestion  - did include sources into project, and it helped me.
... found out what was wrong. I forget to include one of domain classes/types in scheme. 

Now it's ok.

**Comment by jgoelten** [comment]
@HughPH please have a look at rc3 preview version from myget.org. Similar issue is reported over here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1152

I was facing the same error when using ODataQueryOptions<TEntity> as a parameter. Updating to rc3 allowed swagger ui to startup again.

**Comment by domaindrivendev** [comment]
Closing as I believe this is resolved in master and the latest preview version from myget.

**Comment by resthomas** [comment]
@domaindrivendev I have installed the most recent preview version from myget and I am still getting this confusing error.

**Comment by domaindrivendev** [comment]
Can you provide the latest stack trace? If it’s the same as you initially posted then that means you couldn’t possibly have the latest latest preview because several of the classes/methods in that stack trace (and the exception with incomplete message) don’t exist anymore

**Comment by voroninp** [comment]
@domaindrivendev , here is my version of ST:

>System.InvalidOperationException: TODO:
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ObjectSchemaGenerator.GeneratePropertySchema(JsonProperty jsonProperty, Object[] attributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ObjectSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ReferencedSchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(Type type, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass19_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(String statusCode, ApiResponseType apiResponseType, IEnumerable`1 methodAttributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, IEnumerable`1 methodAttributes, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by domaindrivendev** [comment]
That’s not from the latest preview version as several of those types don’t exist in that version. What’s the full version of SB you’re referencing? Have you cleaned your project and ran dotnet restore?

**Comment by voroninp** [comment]
`<PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc2" />`

Yep, removed `bin` and `obj` folders, deleted all swashbuckle packages from `.nuget` folder.

**Comment by domaindrivendev** [comment]
So that's the latest _pre-release_ version but not the latest _preview_ version. Preview versions are generated with every commit to master and hosted on myget.org. See https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore.

Confusing terminology I know :) FWIW, I'm aiming to get the next _pre-release (5.0.0-rc3)_ out very shortly, closely followed by the official 5.0.0 release. But in the meantime, you'll need to live on the edge with the preview versions 😨
