### ISSUE TITLE
Parameters of type IList throw a null reference exception

### ISSUE THREAD

**Issue by markdulfer** [domaindrivendev/Swashbuckle.AspNetCore#1204]
Using Swashbuckle.AspNetCore 5.0.0-rc2
(This works with v4.0.1)

Note: I am unable to change the code from IList to a generic IList<object> for various reasons beyond my control.

Controller method:
```
[HttpGet]
public int Get(System.Collections.IList options)
{
   return 1;
}
```

The DictionarySchemaGenerator seems to handle this case by explicitly checking the item type:
```
var jsonDictionaryContract = (JsonDictionaryContract)ContractResolver.ResolveContract(type);

var keyType = jsonDictionaryContract.DictionaryKeyType ?? typeof(object);
var valueType = jsonDictionaryContract.DictionaryValueType ?? typeof(object);
```

but the ArraySchemaGenerator has no equivalent check.

Exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.SwaggerGen.TypeExtensions.IsNullable(Type type) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\TypeExtensions.cs:line 11
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 44
   at Swashbuckle.AspNetCore.SwaggerGen.ArraySchemaGenerator.GenerateSchemaFor(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\ArraySchemaGenerator.cs:line 25
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 78
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 86
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 86
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 86
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 86
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 86
   at Swashbuckle.AspNetCore.SwaggerGen.ChainableSchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 86
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGen\SchemaGenerator.cs:line 53
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 193
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass11_0.<GenerateParameters>b__1(ApiParameterDescription apiParam) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 174
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameters(ApiDescription apiDescription, SchemaRepository schemaRespository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 173
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 138
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 130
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 90
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath) in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.SwaggerGen\Generator\SwaggerGenerator.cs:line 52
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__5.MoveNext() in Swashbuckle.AspNetCore-master\src\Swashbuckle.AspNetCore.Swagger\SwaggerMiddleware.cs:line 48
```

**Comment by domaindrivendev** [comment]
Fixed by 9dfb26a41bf953be4ddaabc493b56dbb8866b579
