### ISSUE TITLE
Documentation Missing with multiple controllers

### ISSUE THREAD

**Issue by marcscol** [domaindrivendev/Swashbuckle.AspNetCore#1213]
I am getting this error when adding a second controller to my aspnetcore API

System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.Swagger.Schema.set_Minimum(System.Nullable`1<Int32>)'.
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaExtensions.AssignValidationProperties(Schema schema, JsonProperty jsonProperty)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract, Queue`1 referencedTypes)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistry.CreateInlineSchema(Type type, Queue`1 referencedTypes)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRegistry.GetOrRegister(Type type)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateParameter(ApiDescription apiDescription, ApiParameterDescription paramDescription, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 124.2599ms 500

Tried different things like adding multiple documents, nothing appears to happen.

Appreciate any help on this..

Regards.

**Comment by jholovacs** [comment]
I got this when I updated Swashbuckle.AspNetCore.Swagger from 3 to 4 and Swashbuckle.AspNetCore.SwaggerUI from 3 to 4 but did not update Swashbuckle.AspNetCore.SwaggerGen from 3 to 4.  Once I did, the problem went away.

**Comment by domaindrivendev** [comment]
Closing due to inactivity
