### ISSUE TITLE
Adding Swashbuckle.AspNetCore to my ASP.NET Core MVC 3.0 project causes build failure

### ISSUE THREAD

**Issue by jonsagara** [domaindrivendev/Swashbuckle.AspNetCore#1273]
When I add Swashbuckle.AspNetCore 5.0.0-rc3 to my ASP.NET Core MVC 3.0 web application, I get a build failure:

> MSB3073 The command "dotnet "C:\Users\jonsagara\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "C:\Dev\MyApp\src\MyApp\bin\Debug\netcoreapp3.0\MyApp.dll" --file-list "obj\MyApp.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "MyApp" --assets-file "C:\Dev\MyApp\src\MyApp\obj\project.assets.json" --platform "AnyCPU" " exited with code 7

If I copy that command and run it from PowerShell in the project directory, I get the following stack trace:

```
PS C:\Dev\SANDBOX\SwashbuckleAspNetCoreBuildFailure\SwashbuckleAspNetCoreBuildFailure> dotnet "C:\Users\jonsagara\.nuget\packages\microsoft.extensions.apidescription.server\0.3.0-preview7.19365.7\build\/../tools/dotnet-getdocument.dll" --assembly "C:\Dev\SANDBOX\SwashbuckleAspNetCoreBuildFailure\SwashbuckleAspNetCoreBuildFailure\bin\Debug\netcoreapp3.0\SwashbuckleAspNetCoreBuildFailure.dll" --file-list "obj\SwashbuckleAspNetCoreBuildFailure.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v3.0" --output "obj" --project "SwashbuckleAspNetCoreBuildFailure" --assets-file "C:\Dev\SANDBOX\SwashbuckleAspNetCoreBuildFailure\SwashbuckleAspNetCoreBuildFailure\obj\project.assets.json" --platform "AnyCPU"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/cb7dea2a-b2a2-42c5-8f30-db24236af1ae. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/cb7dea2a-b2a2-42c5-8f30-db24236af1ae. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/cb7dea2a-b2a2-42c5-8f30-db24236af1ae. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/cb7dea2a-b2a2-42c5-8f30-db24236af1ae. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
operable program or batch file.


   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<get_KeyVaultTokenCallback>b__8_0(String authority, String resource, String scope)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.Build(Object builder)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveServiceProviderFactory>b__2(String[] args)
   at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.Process(GetDocumentCommandContext context)
PS C:\Dev\SANDBOX\SwashbuckleAspNetCoreBuildFailure\SwashbuckleAspNetCoreBuildFailure>
```

This looks like it's invoking my application and failing on Azure KeyVault configuration, code which is only supposed to run in non-local environments:

```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .ConfigureAppConfiguration(
                    (context, config) =>
                        {
                            // In Azure environments, we use Key Vault for connection strings.
                            // See: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.0#use-managed-identities-for-azure-resources
                            if (context.HostingEnvironment.IsStaging() || context.HostingEnvironment.IsProduction())
                            {
                                // Grab the Key Vault name and Azure AD Application Id from App Settings stored in Portal.
                                var builtConfig = config.Build();

                                // Create an instance of the AzureServiceTokenProvider class without a connection string. When a connection string
                                //   isn't provided, the provider attempts to obtain an access token from Managed identities for Azure resources.
                                var azureServiceTokenProvider = new AzureServiceTokenProvider(connectionString: null);

                                // Create a new KeyVaultClient with the AzureServiceTokenProvider instance token callback.
                                var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

                                // The KeyVaultClient instance is used with a default implementation of IKeyVaultSecretManager that loads all secre
                                //   values and replaces double-dashes (--) with colons (:) in key names.
                                config.AddAzureKeyVault(
                                    vault: $"https://somevault.vault.azure.net/",
                                    client: keyVaultClient,
                                    manager: new DefaultKeyVaultSecretManager()
                                    );
                            }
                        });
```

Is there a way to work around this?

Sample repo with reproduction steps in the readme is located here: https://github.com/jonsagara/SwashbuckleAspNetCoreBuildFailure

Thank you.

**Comment by jonsagara** [comment]
Looks like there is a workaround: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1226#issuecomment-530894591

I'm not clear on how much of Swashbuckle that disables, though. Seems like there is still an underlying issue that needs fixing.

**Comment by domaindrivendev** [comment]
Tracking in #1266

**Comment by domaindrivendev** [comment]
@jonsagara - the workaround doesn't disable any part of Swashbuckle, it just disable some new .NET Core SDK features that leverage Swashbuckle at build time.
