### ISSUE TITLE
NullReferenceException in SwaggerMiddleware.RequestingSwaggerDocument

### ISSUE THREAD

**Issue by kennethcochran** [domaindrivendev/Swashbuckle.AspNetCore#1286]
I'm getting the following exception in Swashbuckle.AspNetCore v4.0.1 when attempting to access the default path ("/swagger/") for the Swagger UI endpoint:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Swashbuckle.AspNetCore.Swagger
  StackTrace:
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RequestingSwaggerDocument(HttpRequest request, String& documentName)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5.MoveNext() 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
```

From examining the source I believe it is occuring on line 72. The `routeValues` dictionary has a key for "documentName" but it's value is null. I imagine I have a configuration error of some kind but I can't for the life of me figure out what I'm missing.

Here is my configuration:

```
services
                .AddSwaggerGen(c =>
                {
                    c.SwaggerDoc("myApi/v1", new Info
                    {
                        //...
                    });
                    c.SwaggerDoc("myOtherApi/v1", new Info
                    {
                        //...
                    });
app
.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/myApi/v1", "My API v1");
                    c.SwaggerEndpoint("/swagger/myOtherApi/v1", "My Other API v1");
                    c.RoutePrefix = string.Empty;
                })
                .UseSwagger(c =>
                {
                    c.RouteTemplate = "swagger/{*documentName}";
                    c.PreSerializeFilters.Add((swaggerDoc, httpReq) =>
                    {
                        swaggerDoc.Host = httpReq.Host.Value;
                        swaggerDoc.Schemes = new List<string> {httpReq.Scheme};
                        swaggerDoc.BasePath = httpReq.PathBase;
                    });
                })
```

**Comment by domaindrivendev** [comment]
@kennethcochran - if this is still a problem with the latest version, could you please create a minimal app (i.e. start from an empty proj) that repro's the issue and post to github so I can pull it down and troublehsoot.

**Comment by domaindrivendev** [comment]
Closing due to inactivity
