### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.OpenApi,

### ISSUE THREAD

**Issue by nezoic** [domaindrivendev/Swashbuckle.AspNetCore#1300]
When running against a .netcore 2.2 project I get the following exception:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.OpenApi, Version=1.1.1.0, Culture=neutral, PublicKeyToken=3f5743946376f042'. The system cannot find the file specified.
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 99

**Comment by navi-dev** [comment]
For me using the swagger-codegen-cli-3.0.9.jar file resolved the issue.

you can directly download the jar file from 
`https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/`

**Comment by Lonli-Lokli** [comment]
@domaindrivendev 
Is there another workaround? I currently have netcore 2.1 with swagger v4 and do not want to upgrade to v5. As for me, swagger global tool should have all the dependencies inside and do not rely on app itself.

**Comment by domaindrivendev** [comment]
Closing in favor of #1699, which captures all of the outstanding compatibility issues. That issue is being addressed as a top priority.

Also ...
> As for me, swagger global tool should have all the dependencies inside and do not rely on app itself

The tool needs to host and run the application, including all of it's dependencies, and therefore has to rely on the app.
