### ISSUE TITLE
System.OverflowException when processing enums

### ISSUE THREAD

**Issue by kapitanov** [domaindrivendev/Swashbuckle.AspNetCore#1435]
Swashbuckle generators crashes when tryng to process an enum that contains a numeric value greater than `int.MaxValue`:

```csharp
[Flags]
public enum Flags : uint
{
    None = 0,
    Max = uint.MaxValue, //  would fail to process this value
}
```

Trying to generate an OpenAPI definition from this enum would result in exception:

```
Unhandled exception. System.OverflowException: Value was either too large or too small for an Int64.
   at System.Convert.ThrowInt64OverflowException()
   at System.UInt64.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ToInt64(Object value, IFormatProvider provider)
   at System.Enum.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.TryCast[T](Object value, T& typedValue)
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.CreateFor(OpenApiSchema schema, Object value)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonEnumHandler.<>c__DisplayClass3_0.<CreateDefinitionSchema>b__1(Object value)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonEnumHandler.CreateDefinitionSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass18_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Bug.Program.Main() in D:\opensource\swashbuckle-enum-overflow-reproduce\Program.cs:line 44
```

Affected version: `5.0.0-rc5`.

I've written a small app to reproduce: [github.com/kapitanov/swashbuckle-enum-overflow-reproduce](https://github.com/kapitanov/swashbuckle-enum-overflow-reproduce).

**Comment by iskandarumidov** [comment]
It looks like Swagger is relying on OpenAPI to do what you want. However OpenAPI itself does not support unsigned data types [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/233). Someone proposed to introduce new data formats [here](https://github.com/OAI/OpenAPI-Specification/issues/607) but the issue was closed in favor of [this one](https://github.com/OAI/OpenAPI-Specification/issues/845).

The [documentation](https://swagger.io/specification/#dataTypeFormat) doesn’t list unsigned data types.

**Comment by Temurson** [comment]
I also found that `uint` and `ulong` are just not supported by **Swagger**. Apparently, you are not the first one confused by this little detail, so I suggest the docs should note that unsigned integer types are not supported. I believe this could be done either in this project's docs or in [Swagger](https://swagger.io/docs/specification/data-models/data-types/) docs. However, I failed to find a place (repo) where this suggestion could be made. Could someone show me where it is and I would be happy to open a PR.

**Comment by domaindrivendev** [comment]
Due to the lack of native support in Swagger / OpenAPI for "unsigned" data types, this requires a little more thought. I'm thinking the generator _could_ be a little smarter in the way it describes numeric types in general. For example, "unsigned" numerics could be bumped up to the next size format (e.g. `uint` could have a "Swagger" format of `int64` instead of `int32`) to account for the higher max

**Comment by CodyBatt** [comment]
I just ran into this also. I'm migrating to the latest version of swagger/swashbuckle and it was not easy to track down the problem. The 500 error when trying to fetch swagger.json in javascript has no context and the log message above doesn't reference any types so it was just a process of elimination for me to zero in on the controller that caused the problem, and then I found that it was due to an enum defined like this:

public enum QueryOption : uint

Even if there's no support in OpenAPI for unsigned data types, handling this exception and providing context would help in the meantime.
