### ISSUE TITLE
[.NET Core 3.1] How to hide OData endpoints in new version of Shwashbuckle (vr 5.0.0-rc5)?

### ISSUE THREAD

**Issue by MDzyga** [domaindrivendev/Swashbuckle.AspNetCore#1442]
Hi,
I updated my project to new version of .NET Core (3.1) & I have a problem with OData endpoints. They broke my documentation because they aren't supported by Swashbuckle. I have tried to define Document filter but it doesn't work.

Swagger Gen configuration
```
services.AddSwaggerGen(c =>
{
     c.SwaggerDoc($"v{Configuration["Version"]}", new OpenApiInfo { ... });
     ...
     c.DocumentFilter<SwaggerHideFilter>();
});
```

Swagger Hide Filter
```
public class SwaggerHideFilter : IDocumentFilter
{
     public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            foreach (var contextApiDescription in context.ApiDescriptions)
            {
                var actionDescriptor = (ControllerActionDescriptor)contextApiDescription.ActionDescriptor;

                if (actionDescriptor.ControllerTypeInfo.GetCustomAttributes(typeof(SwaggerHideAttribute), false).Any() ||
                    actionDescriptor.MethodInfo.GetCustomAttributes(typeof(SwaggerHideAttribute), false).Any())
                {
                    var key = "/" + contextApiDescription.RelativePath.TrimEnd('/');
                    swaggerDoc.Paths.Remove(key);
                }
            }
        }
}
```

Earlier the solution was define in MVC Service media type but in version of .NET Core 3.1 it doesn't work.
```
services.AddMvc(op =>
{
      foreach (var formatter in op.OutputFormatters.OfType<ODataOutputFormatter>() .Where(it => !it.SupportedMediaTypes.Any()))
      {
             formatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.mock-odata"));
      }

       foreach (var formatter in op.InputFormatters .OfType<ODataInputFormatter>().Where(it => !it.SupportedMediaTypes.Any()))
       {
             formatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.mock-odata"));
       }
});
```

**Comment by domaindrivendev** [comment]
See the readme for the recommended way to omit certain operations - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#omit-arbitrary-operations

**Comment by MDzyga** [comment]
It doesn't work too. I set this attribute on all OData Controllers, their Actions & abstract class.
I always get a error message:

> {"message":"No media types found in 'Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types. "}

**Comment by domaindrivendev** [comment]
What action are you doing to produce that message? If you provide a concise set of repro steps it will be easier to troubleshoot

**Comment by MDzyga** [comment]
I have base ODataController (vr of Microsoft.AspNet.OData is 7.3.0)

```
[ApiExplorerSettings(IgnoreApi = true)]
public abstract class BaseODataController : ODataController
{
     protected virtual async Task<IActionResult> Paginate<TEntity, TProjection>(IQueryable<TEntity> query, ODataQueryOptions<TEntity> options, bool enableCloneFilter = true) 
    { 
        ... 
        return OK(items);
    }
}
```

Next I have 3 Controllers which inherit by BaseODataController and a few (~20) endpoints which execute Paginate method.

In my Startup class I configured Odata like beloew:
```
public void ConfigureServices(IServiceCollection services)
{
   services.AddOData();
   services.AddTransient<ODataModel>();
}

public void Configure(IApplicationBuilder app)
{
     app.UseSwagger();
     app.UseSwaggerUI(c => {});

     app.UseRouting();

     app.UseCors(...);

      app.UseAuthentication();
      app.UseAuthorization();

     app.UseEndpoints(endpoints =>
     {
                endpoints.MapHub<BackgroundStatus>("/backgroundservice");
                endpoints.MapControllers();
    });

    app.UseMvc(routes =>
    {
          routes.Select().Filter().OrderBy().MaxTop(null).Count();
          routes.MapODataServiceRoute("ODataRoutes", "odata", ODataModel.GetEdmModel(app.ApplicationServices));
          routes.EnableDependencyInjection();
    });
}
```

**Comment by domaindrivendev** [comment]
That’s the setup. What do you do then to see the error?

**Comment by MDzyga** [comment]
I configured my solution to show Documentation when application is debugging. So the next I run my application.
![image](https://user-images.githubusercontent.com/38663990/71623199-16e28e80-2bdb-11ea-8829-07fe96f09d14.png)

**Comment by domaindrivendev** [comment]
So hitting the /swagger endpoint shows the error? It’s not the error format I’d expect from that page

**Comment by MDzyga** [comment]
My error page looks like 
![image](https://user-images.githubusercontent.com/38663990/71623552-b1dc6800-2bdd-11ea-967d-a5f35da0b53d.png)
I can check an error message in browser console (Network tab)

**Comment by domaindrivendev** [comment]
Can you navigate to /swagger/v1/swagger.json directly? That might give a more detailed exception, ideally a stack trace

**Comment by MDzyga** [comment]
![image](https://user-images.githubusercontent.com/38663990/71625183-c2451080-2be6-11ea-9ff9-f3a683158d37.png)

**Comment by domaindrivendev** [comment]
Could you try enabling the Dev Exception page middleware in Startup.cs, might give us the additional detail we need? IIRC it’s “app.UseDeveloperExceptionPage()”

**Comment by MDzyga** [comment]
This is stacktrace:

```
System.InvalidOperationException: No media types found in 'Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.
   at Microsoft.AspNetCore.Mvc.Formatters.OutputFormatter.GetSupportedContentTypes(String contentType, Type objectType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiResponseTypeProvider.CalculateResponseFormats(ICollection`1 responseTypes, MediaTypeCollection declaredContentTypes)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiResponseTypeProvider.GetApiResponseTypes(IReadOnlyList`1 responseMetadataAttributes, Type type, Type defaultErrorType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiResponseTypeProvider.GetApiResponseTypes(ControllerActionDescriptor action)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.CreateApiDescription(ControllerActionDescriptor action, String httpMethod, String groupName)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) System.InvalidOperationException: No media types found in 'Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.SupportedMediaTypes'. Add at least one media type to the list of supported media types.
   at Microsoft.AspNetCore.Mvc.Formatters.OutputFormatter.GetSupportedContentTypes(String contentType, Type objectType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiResponseTypeProvider.CalculateResponseFormats(ICollection`1 responseTypes, MediaTypeCollection declaredContentTypes)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiResponseTypeProvider.GetApiResponseTypes(IReadOnlyList`1 responseMetadataAttributes, Type type, Type defaultErrorType)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiResponseTypeProvider.GetApiResponseTypes(ControllerActionDescriptor action)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.CreateApiDescription(ControllerActionDescriptor action, String httpMethod, String groupName)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.DefaultApiDescriptionProvider.OnProvidersExecuting(ApiDescriptionProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.GetCollection(ActionDescriptorCollection actionDescriptors)
   at Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescriptionGroupCollectionProvider.get_ApiDescriptionGroups()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by MDzyga** [comment]
@domaindrivendev I think the problem can be related with generating endpoints to XML files. I suppose OData endpoints shouldn't be there but I see them in my file

**Comment by MDzyga** [comment]
@domaindrivendev wil you fix it or help me with proper configuration?

**Comment by MDzyga** [comment]
The solution is:

```
services.AddMvcCore(options =>
{
   foreach (var outputFormatter in options.OutputFormatters.OfType<OutputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
   {
          outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
    }

   foreach (var inputFormatter in options.InputFormatters.OfType<InputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
   {
         inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
   }
});
```

**Comment by sc-starman** [comment]
> The solution is:
> 
> ```
> services.AddMvcCore(options =>
> {
>    foreach (var outputFormatter in options.OutputFormatters.OfType<OutputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
>    {
>           outputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
>     }
> 
>    foreach (var inputFormatter in options.InputFormatters.OfType<InputFormatter>().Where(x => x.SupportedMediaTypes.Count == 0))
>    {
>          inputFormatter.SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/prs.odatatestxx-odata"));
>    }
> });
> ```
I use your solution here but I got the same error again.
Can you help me with that?
