### ISSUE TITLE
Can't generate swagger.json with "new" modifier (5.0.0-rc5)

### ISSUE THREAD

**Issue by treisska** [domaindrivendev/Swashbuckle.AspNetCore#1465]
Hello,

I have some issues generating the swagger.json file when using the "new" modifier in my models.
Here is the stacktrace I get :

```
System.ArgumentException: An item with the same key has already been added. Key: issue
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Swashbuckle.AspNetCore.SwaggerGen.JsonObjectHandler.CreateDefinitionSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.<>c__DisplayClass4_1.<GenerateSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.CreateReferenceSchema(Type type, SchemaRepository schemaRepository, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGeneratorBase.GenerateSchema(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass18_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Basically we are using the "new" modifier to hide another property with the same name.

```
    public class Demo : DemoLight
    {
        public new Issue Issue { get; set; }
    }
```
```
    public class DemoLight
    {
        public IssueLight Issue { get; set; }
    }
```

Here is a repo with a project that reproduce the issue : https://github.com/treisska/swashbuckle-issue-demo. Just launch the project and navigate to /swagger to get the error.

**Comment by domaindrivendev** [comment]
Are you using `Newtonsoft` or the new `System.Text.Json` serializer that ships by default with ASP.NET Core 3.0 and beyond?

If it's the latter, then this is a mute point because `STJ` does not support serialization of properties with the new modifier. See https://github.com/dotnet/corefx/issues/41338. So, Swashbuckle aside, this implementation for your API simply won't work.

If it's the former, then you should ensure that Swashbuckle is configured to honor `Newtonsoft` behavior instead of `STJ` as described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft). If you do this, Swashbuckle _should_ support your use-case just fine.

**Comment by treisska** [comment]
Thank you for your answer. I was using `STJ` indeed. I was not aware of this issue, that is really a shame.
I guess I'll switch back to `Newtonsoft`.

**Comment by ufalak** [comment]
I did this but the error is still happening to me
