### ISSUE TITLE
[5.0.0] Missing Method 'CreateSchema' from Newtonsoft Libraries 

### ISSUE THREAD

**Issue by matthawley** [domaindrivendev/Swashbuckle.AspNetCore#1482]
I upgraded from v5.0.0-rc5 to v5.0.0 and on startup I'm now receiving the following errors:

```
ystem.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'CreateSchema' in type 'Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftArrayHandler' from assembly 'Swashbuckle.AspNetCore.Newtonsoft, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'CreateSchema' in type 'Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftDictionaryHandler' from assembly 'Swashbuckle.AspNetCore.Newtonsoft, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'CreateSchema' in type 'Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftEnumHandler' from assembly 'Swashbuckle.AspNetCore.Newtonsoft, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'CreateSchema' in type 'Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftLinqTypeHandler' from assembly 'Swashbuckle.AspNetCore.Newtonsoft, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'CreateSchema' in type 'Swashbuckle.AspNetCore.Newtonsoft.NewtonsoftObjectHandler' from assembly 'Swashbuckle.AspNetCore.Newtonsoft, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Stack trace:
```
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllers(IEndpointRouteBuilder endpoints)
```

I'm using 5.0.0 for both packages, and 12.0.3 for Newtonsoft on .NET Core 3.1

**Comment by matthawley** [comment]
I updated only the 2 packages today and I didn't have this issue. Wondering if it was another package that I upgraded at the time that caused this. I'm currently working on re-introducing those and I'll see if this occurs again.

**Comment by matthawley** [comment]
I'm not sure why this occurred, but it's no longer doing it.
