### ISSUE TITLE
Bug: app.UsePathBase(string) + SwaggerOptions.SerializeAsV2 = true does not work

### ISSUE THREAD

**Issue by jinhong-** [domaindrivendev/Swashbuckle.AspNetCore#1495]
Version 5.0.0
```
public void Configure(IApplicationBuilder app)
{
  app.UsePathBase("whatever");
  app.UseSwagger(c => { c.SerializeAsV2 = true; });
}
```
When setting the path base and then configuring swagger to serialize as v2, I was not able to load the swagger.json document and instead was presented with an error.

Here is the stack trace:
```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.OpenApi.Models.OpenApiDocument.WriteHostInfoV2(IOpenApiWriter writer, IList`1 servers)
   at Microsoft.OpenApi.Models.OpenApiDocument.SerializeAsV2(IOpenApiWriter writer)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.RespondWithSwaggerJson(HttpResponse response, OpenApiDocument swagger)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jinhong-** [comment]
Looks like this might be a bug inside Microsoft.OpenApi library. They made a slight change in version v1.2.0 which allows relative paths
https://github.com/microsoft/OpenAPI.NET/blob/3c91a1d944aea9119967a7a66b2e0096918ad8f1/src/Microsoft.OpenApi/Models/OpenApiDocument.cs#L258

**Comment by muratkuru** [comment]
@domaindrivendev

hi, is there any plain for upgrade openapi version in this repo?

**Comment by domaindrivendev** [comment]
See e92e60c
