### ISSUE TITLE
More than one file as arguments of action

### ISSUE THREAD

**Issue by tchrobocek** [domaindrivendev/Swashbuckle.AspNetCore#1529]
Hello, 

We migrated from netcore 2.2 to netcore 3.1 and as a part of that we upgraded Swashbuckle.AspNetCore to 5.0.0

After an upgrade I couldn't get the swagger to work again as it was throwing an exception

> System.ArgumentException: An item with the same key has already been added. Key: ContentType
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchemaFromFormParameters(IEnumerable`1 formParameters, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromFormParameters(ApiDescription apiDescription, SchemaRepository schemaRepository, IEnumerable`1 formParameters)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

After some digging I found this action is causing problems. The solution is to have both arguments wrapped in some class, but I would rather have them separated.
```c#
public IActionResult GenerateDocument([FromForm] [Required] IFormFile template,
            [FromForm] [Required] IFormFile data)
```

Thank you!

**Comment by tomasszabo** [comment]
Same problem here. Needed to ignore such methods with `[ApiExplorerSettings(IgnoreApi = true)]` in order to have at least some output from Swagger.

**Comment by domaindrivendev** [comment]
Dup of #1348. Long story short - remove the `[FromForm]` attirbutes - they're not needed by ASP.NET Core and they cause issues with `ApiExplorer` the .NET metadata layer that Swashbuckle is built on top of.
