### ISSUE TITLE
NullReferenceException in SwaggerGen

### ISSUE THREAD

**Issue by spanevin** [domaindrivendev/Swashbuckle.AspNetCore#1570]
Version 5.1.0 (5.0.0 works well in the same project)

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.SwaggerGen.MemberInfoExtensions.GetInlineOrMetadataTypeAttributes(MemberInfo memberInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerMetadata serializerMetadata, Sche
maRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, Mem
berInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateArraySchema(SerializerMetadata serializerMetadata, Schem
aRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, Mem
berInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerMetadata serializerMetadata, Sche
maRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, Mem
berInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerMetadata serializerMetadata, Sche
maRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, Mem
berInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateArraySchema(SerializerMetadata serializerMetadata, Schem
aRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, Mem
berInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepo
sitory schemaRespository)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elemen
tSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepositor
y schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaReposito
ry schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaReposito
ry schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaReposit
ory schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository s
chemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__4.MoveNext()`

**Comment by domaindrivendev** [comment]
@spanevin a small contribution would be much appreciated here. Could you possibly pull down the source and debug to identify where the NRE is occurring?

**Comment by spanevin** [comment]
@domaindrivendev I understand it could help you but unfortunately I can't share the code of a real application, and I have no simple example for reproduction yet. If I get some - I'll share it.

Some additional details which I forgot to share in the initial message: my service is AspNetCore2.2-based with net48 framework target, it uses customized Newtonsoft.JSON-based serialization so when I updated Swashbuckle.AspNetCore from 4.x to 5.0 I had to install Swashbuckle.AspNetCore.Newtonsoft and use services.AddSwaggerGenNewtonsoftSupport(), without it I was getting an error about conflicting schema ids which could be solved using SwaggerGenOptions.CustomSchemaIds(...) since there are inherited types with the same name but in different namespaces.

**Comment by Adriien-M** [comment]
I have the same issue when I upgrade to 5.0.0 to 5.0.1

**Comment by domaindrivendev** [comment]
@spanevin and @Adriien-M - this definitely sounds like an issue that needs to be addressed. If either of you could put together a simple example project that repro's the issue then I'd be happy to get it resolved ASAP.

**Comment by spanevin** [comment]
@domaindrivendev 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs#L12

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.declaringtype?view=netstandard-2.0

memberInfo.DeclaringType can be null, can't it be our issue?

**Comment by domaindrivendev** [comment]
I think this should be fixed by #1576

**Comment by spanevin** [comment]
> 
> 
> I think this should be fixed by #1576

Works in 5.2.0, thanks all
