### ISSUE TITLE
SchemaId already used for different type

### ISSUE THREAD

**Issue by MRVDH** [domaindrivendev/Swashbuckle.AspNetCore#1607]
I'm getting this error because I think that for some reason it conflicts with a class that I have called `Module`. Changing the name of that class is not an option, so is there a way to fix this? Maybe the best question is; why does this error even occur at all?

`Can't use schemaId "$Module" for type "$System.Reflection.Module". The same schemaId is already used for type "$Prjct.Data.Models.Module"`

Swashbuckle.AspNetCore.Swagger version 5.2.1

Stacktrace:
```
Can't use schemaId "$Module" for type "$System.Reflection.Module". The same schemaId is already used for type "$SAM.Data.Models.Module"
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.ReserveIdFor(Type type, String schemaId)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateArraySchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateArraySchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateObjectSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass6_0.<GenerateReferencedSchema>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.GetOrAdd(Type type, String schemaId, Func`1 factoryMethod)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateArraySchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateInlineSchema(SerializerContract serializerContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromBodyParameter(ApiDescription apiDescription, SchemaRepository schemaRepository, ApiParameterDescription bodyParameter)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
```

**Comment by MRVDH** [comment]
Fixed by using

```
services.AddSwaggerGen(options =>
{
    options.CustomSchemaIds(type => type.ToString());
}
```

From issue #1431: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1431#issuecomment-578418266

**Comment by MRVDH** [comment]
@domaindrivendev Not sure who the repo owner is but judging by the likes I'm not the only one with this issue. maybe it could get looked into?

**Comment by domaindrivendev** [comment]
By default, SB uses the short (unqualified name) which has its benefits because it keeps the docs simpler but also it’s downside if model names are duplicated in different namespaces. In this case, you can provide a custom naming strategy as described above.


That’s it! Not sure what else needs to be “looked into”. Are expecting SB to do something else out of the box? If so, please elaborate on proposed behavior?

**Comment by PureKrome** [comment]
@domaindrivendev 👋🏻 

> Not sure what else needs to be “looked into”.

Instead of a 'global' setting using `options.CustomSchemaIds` .. is it possible to set this via an _attribute_ on the Action Method?

something like:

```
[HttpGet("users/{userId}", Name = "Users_GetAUser")]
[ProducesResponseType(typeof(GetUser.Response), (int)HttpStatusCode.OK), Name = "Users_GetAUser"]
[ProducesResponseType((int)HttpStatusCode.NotFound)]
public async Task<IActionResult> GetUser([FromRoute] GetUser.Query request, CancellationToken cancellationToken)
{
 ...
}
```

notice the `Name = "Users_GetAUser"` ? so we define the name of the response class, there.

**Comment by thesagarchavan** [comment]
if you don't want to expose fullname of your model then 
`services.AddSwaggerGen(options =>
{
    options.CustomSchemaIds(type => $"{type.Name}_{System.Guid.NewGuid()}");
});`

**Comment by jbojcic1** [comment]
@domaindrivendev what if the type is from different versions? So if I have type called T in v1 and v2 why is that a collision if separate swagger file is created for each version

**Comment by SGVoid** [comment]
In my case, the issue was triggered by a couple of nested types with the same name, but their parents were completely different. 

So,

```csharp
services.AddSwaggerGen(options =>
{
    options.CustomSchemaIds(type => string.Join('.', new[] { type.ReflectedType?.Name, type.Name }.Where(x => x != null)));
});
```

worked fine for me

**Comment by icnocop** [comment]
> In my case, the issue was triggered by a couple of nested types with the same name, but their parents were completely different.

Swashbuckle.AspNetCore should be able to re-use the same schema id for the same types, even if they're nested in different classes, right?

I could not find another open issue for that scenario, so I think a new issue should be created.

**Comment by GlennPiper** [comment]
@johnnyreilly had a good idea, but I found that it kept incrementing the count with each view of the swagger page or file, so I made a bit of a tweak to it to make it able to be repeatably called:
`
        private readonly Dictionary<string, List<string>> _schemaNameRepetition = new();

        // borrowed from https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/95cb4d370e08e54eb04cf14e7e6388ca974a686e/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGeneratorOptions.cs#L44
        private string DefaultSchemaIdSelector(Type modelType)
        {
            if (!modelType.IsConstructedGenericType) return modelType.Name.Replace("[]", "Array");

            var prefix = modelType.GetGenericArguments()
                .Select(genericArg => DefaultSchemaIdSelector(genericArg))
                .Aggregate((previous, current) => previous + current);

            return prefix + modelType.Name.Split('`').First();
        }

        public string GetSchemaId(Type modelType)
        {
            string id = DefaultSchemaIdSelector(modelType);

            if (!_schemaNameRepetition.ContainsKey(id))
                _schemaNameRepetition.Add(id, new List<string>());

            var modelNameList = _schemaNameRepetition[id];
            var fullName = modelType.FullName;
            if (!modelNameList.Contains(fullName))
                modelNameList.Add(fullName);

            int index = modelNameList.IndexOf(fullName);

            return $"{id}{(index >= 1 ? index.ToString() : "")}";
        }
    }
`

**Comment by johnnyreilly** [comment]
Thanks for sharing @GlennPiper - I use mine in script form and so I don't hit this. I can't quite make out what is different in yours... Can you clarify please?

**Comment by mshgh** [comment]
the same here ;) happy to found this discussion. In my case the Id can be made unique by adding last part of namespace, but what I have realized we do not need to copy&paste any source code from SB. It is actually available to us. So ultimate solution for my use-case is this
```csharp
var defaultSchemaIdSelector = swaggerGenOptions.SchemaGeneratorOptions.SchemaIdSelector;
swaggerGenOptions.CustomSchemaIds(modelType => {
    var defaultId = defaultSchemaIdSelector(modelType);
    var prefix = modelType.Namespace?.Split(".").Last();
    return String.IsNullOrEmpty(prefix) ? defaultId : String.Concat(prefix, ".", defaultId);
});
```

I really love the idea of keeping list of types with collisions and use the index to make the Id unique. Just have you considered to store in the list the `Type` directly instead of its string representation? `Dictionary<string, List<Type>>`
I believe this will simplify it a bit.

@SwashBuckle to me it looks like great idea to have this automatic number-based decoration as a part of the library. Not inside the `SchemaIdSelector` itself, but outside of it. This way everybody has opportunity to ensure there are unique meaningful Ids. But there will be fallback strategy in case the uniqueness fails. In this case adding sequence number is probably the best approach aligned with your requirement to keep the Ids short. To me much better then throwing an exception.

**Comment by dcamarenaAZO** [comment]
Hi folks, in my case a colleague with exactly the same source code (fresh clone) could start the application without any problem. On my machine the mentioned error occurs. This, I can't understand at all. Adding one of the mentioned solutions helped. 

Any idea why this could happen?

**Comment by dcamarenaAZO** [comment]
@martincostello I'll try to create one.
