### ISSUE TITLE
[FromQuery] parameter of type which contains IList<string> property results in error 'System.NotSupportedException: Collection format None is not supported.'

### ISSUE THREAD

**Issue by Terra-jin** [domaindrivendev/Swashbuckle.AspNetCore#1701]
Hi,

I use Swashbuckle 5.4.1, dotnet core 3.1 and autorest 3.0.6282. In our c# code, there's an endpoint that gets a [FromQuery] parameter, which is of type PagingOptions that contains two string array properties (see below).

I get the following error:

This does not happen if I change the parameter to type string. It seems to happens with arrays, though I don't see why.

```
FATAL: System.NotSupportedException: Collection format None is not supported.
   at AutoRest.CSharp.ClientModelExtensions.GetSeparator(CollectionFormat format) in /home/vsts/work/1/s/src/vanilla/ClientModelExtensions.cs:line 245
   at AutoRest.CSharp.ClientModelExtensions.GetFormattedReferenceValue(Parameter parameter, String clientReference) in /home/vsts/work/1/s/src/vanilla/ClientModelExtensions.cs:line 220
   at AutoRest.CSharp.Model.MethodCs.BuildUrl(String variableName) in /home/vsts/work/1/s/src/vanilla/Model/MethodCs.cs:line 392
   at AutoRest.CSharp.vanilla.Templates.Rest.Client.MethodBodyTemplateRestCall.<ExecuteAsync>d__1.MoveNext() in /home/vsts/work/1/s/src/obj/Razor/vanilla/Templates/Rest/Client/MethodBodyTemplateRestCall.cshtml:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString() in /home/vsts/work/1/s/autorest.common/src/Template.cs:line 217
   at AutoRest.Core.Template`1.Include[TU,TV](TU template, TV templateModel) in /home/vsts/work/1/s/autorest.common/src/Template.cs:line 147
   at AutoRest.CSharp.vanilla.Templates.Rest.Client.MethodTemplate.<ExecuteAsync>d__1.MoveNext() in /home/vsts/work/1/s/src/obj/Razor/vanilla/Templates/Rest/Client/MethodTemplate.cshtml:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString() in /home/vsts/work/1/s/autorest.common/src/Template.cs:line 217
   at AutoRest.Core.Template`1.Include[TU,TV](TU template, TV templateModel) in /home/vsts/work/1/s/autorest.common/src/Template.cs:line 147
   at AutoRest.CSharp.vanilla.Templates.Rest.Client.ServiceClientTemplate.<ExecuteAsync>d__1.MoveNext() in /home/vsts/work/1/s/src/obj/Razor/vanilla/Templates/Rest/Client/ServiceClientTemplate.cshtml:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext() in /home/vsts/work/1/s/autorest.common/src/CodeGenerator.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateServiceClient>d__13`1.MoveNext() in /home/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateClientSideCode>d__12.MoveNext() in /home/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateRestCode>d__19.MoveNext() in /home/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<Generate>d__20.MoveNext() in /home/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.Program.<ProcessInternal>d__4.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /home/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
  Error: Plugin csharp reported failure.
```

Here's the c# code (sensitive information omitted / hidden):

```
[HttpGet("overeenkomst/{nummer}")]
        [ProducesResponseType(typeof(PagedResult<Boeking>), (int) HttpStatusCode.OK)]
        [ProducesResponseType((int)HttpStatusCode.UnprocessableEntity)]
        [SwaggerOperation(OperationId = "GetBoekingenByOvereenkomst")]
        public async Task<ActionResult> GetBoekingenByOvereenkomst(string nummer, [FromQuery] PagingOptions options)
        {
// omitted
        }
```

The PagingOptions class:

`````
public class PagingOptions
  {
    public string GlobalSearchTerm { get; set; }

    public int Start { get; set; }

    [Required]
    [Range(1, 2147483647)]
    public int Take { get; set; }

    public IList<string> SearchColumns { get; set; }

    public IList<string> SearchValues { get; set; }

    public string SortColumn { get; set; }

    public Direction SortDirection { get; set; }
  }
`````

**Comment by Terra-jin** [comment]
Solved by manually adding style: form to the array parameters:

```
    public class QueryArramParamFilter : IParameterFilter
    {
        public void Apply(OpenApiParameter parameter, ParameterFilterContext context)
        {
            if (parameter.In.HasValue && parameter.In.Value == ParameterLocation.Query)
            {
                if (parameter.Schema?.Type == "array")
                {
                    parameter.Style = ParameterStyle.Form;
                }
            }
        }
    }

```

**Comment by domaindrivendev** [comment]
Will investigate why this isn’t happening automatically

**Comment by domaindrivendev** [comment]
So ... Swashbuckle doesn't do this automatically but I think that's because the [OpenAPI spec](https://swagger.io/specification/) states that `form` should be the default style for any query parameters:

> Describes how the parameter value will be serialized depending on the type of the parameter value. Default values (based on value of in): for query - form; for path - simple; for header - simple; for cookie - form.

So, one could argue that Autorest isn't honoring this default correctly.

**Comment by Terra-jin** [comment]
Check, thx. Logged [issue](https://github.com/Azure/autorest/issues/3519) with autorest.
