### ISSUE TITLE
BUG: Application is incompatible with Microsoft.OpenAPI 1.2.0, but this package version is allowed in package config.

### ISSUE THREAD

**Issue by korifeich** [domaindrivendev/Swashbuckle.AspNetCore#1717]
Package Swashbuckle.AspNetCore.Swagger - latest version

Steps to reproduce:
- Setup base project with Swagger Connected and swaggergen enabled
- Add API endpoint that contains default parameter
- Add Microsoft.OpenAPI package version 1.2.0 to project
- Try to access swagger.json

Result: Internal Error appear. Stack Trace details:
```
System.MissingMethodException: Method not found: 'Void Microsoft.OpenApi.Any.OpenApiString..ctor(System.String)'.
   at Swashbuckle.AspNetCore.SwaggerGen.OpenApiAnyFactory.CreateFor(OpenApiSchema schema, Object value)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.ApplyParameterMetadata(OpenApiSchema schema, Type type, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass10_0.<GenerateParameters>b__1(ApiParameterDescription apiParam)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameters(ApiDescription apiDescription, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
```

The issue is because Microsoft.OpenAPI v 1.2.0 contains no constructor for `OpenApiString` class with only string input parameter.

Fix suggestion: Restrict max Microsoft.OpenAPI version in Swashbuckle.AspNetCore.Swagger project not to include v 1.2.0

**Comment by LeroyK** [comment]
OpenAPI.NET should have increased its major version with a breaking API change. I have already created https://github.com/microsoft/OpenAPI.NET/issues/487 in the OpenAPI repository that addresses this issue. Just linking it here since the issue also appeared for me via Swashbuckle.

**Comment by CumpsD** [comment]
Or Swashbuckle.AspNetCore.Swagger can move to 1.2.0 of OpenApi, that solves it too I guess.

**Comment by LeroyK** [comment]
That would only solve this issue for projects that don't reference any external projects that rely on OpenAPI.NET that have incompatible APIs.

**Comment by CumpsD** [comment]
True, but the other way around too of course. If somebody has a reference on something that references 1.2.0, they won't be able to do anything since nuget resolution will block it.

The clean solution is Microsoft fixes it and unlists the broken version I think

**Comment by chad-vogel** [comment]
we are having this issue too, Microsoft should fix it because they should not be introducing a breaking change like this in minor update

**Comment by CumpsD** [comment]
The PR just got merged https://github.com/microsoft/OpenAPI.NET/pull/489

**Comment by CumpsD** [comment]
Another identical issue was left, new PR is open https://github.com/microsoft/OpenAPI.NET/pull/492

**Comment by CumpsD** [comment]
PR got merged, the other version got delisted. 1.2.2 has no breaking changes now.

**Comment by IanKemp** [comment]
So can this issue be closed now? Since Microsoft.OpenAP 1.2.0 is no longer available?

**Comment by domaindrivendev** [comment]
Updated to use `1.2.3` as lower bound. See 341751b
