### ISSUE TITLE
endpoint with multiple IFormFile parameters cannot be parsed

### ISSUE THREAD

**Issue by christianAtSuddath** [domaindrivendev/Swashbuckle.AspNetCore#1786]
In a dotnet core api project, converted from dotnet core 2.2 to 3.1 upgrading swashbuckle to 5.5.1,
The following endpoint 
```[HttpPost]
        [Route("", Name = "CreateInvoice")]
        public async Task<ActionResult> PostInvoiceAsync([FromForm]string invoiceInfo, 
                                                            [FromForm] bool isBatch, 
                                                            [FromForm] IFormFile invoiceAttachment, 
                                                            [FromForm] IFormFile multiRecordInvoiceAttachment) {
// omitted
}
```
caused this error:
```
System.ArgumentException: An item with the same key has already been added. Key: ContentType
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchemaFromFormParameters(IEnumerable`1 formParameters, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromFormParameters(ApiDescription apiDescription, SchemaRepository schemaRepository, IEnumerable`1 formParameters)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I cloned the SwaggerGen source code, included the necessary swashbuckle projects in my solution and modified **SwaggerGenerator.cs** (around line 360):

**before:**
`properties.Add(name, schema);`

**after:**

```
try
                {
                    properties.Add(name, schema);
                } 
       catch(Exception ex)
                {
                    Debug.Print($"{ex.Message}: could not add {name} for {formParameter.ParameterDescriptor.Name} : {formParameter.ParameterDescriptor.ParameterType.Name}");
                }
```

This resulted in the following output:

```
An item with the same key has already been added. Key: ContentType: could not add ContentType for multiRecordInvoiceAttachment : IFormFile
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An item with the same key has already been added. Key: ContentDisposition: could not add ContentDisposition for multiRecordInvoiceAttachment : IFormFile
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An item with the same key has already been added. Key: Headers: could not add Headers for multiRecordInvoiceAttachment : IFormFile
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An item with the same key has already been added. Key: Length: could not add Length for multiRecordInvoiceAttachment : IFormFile
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An item with the same key has already been added. Key: Name: could not add Name for multiRecordInvoiceAttachment : IFormFile
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An item with the same key has already been added. Key: FileName: could not add FileName for multiRecordInvoiceAttachment : IFormFile
```

**This is new in this version. In version 4.0.1, the same endpoint did not generate an error.**

Also, it would be nice, if there was a "debug" setting that could be enabled, so that it would be easier to see the problem.

**Comment by domaindrivendev** [comment]
Long story short - you shouldn't be decorating parameters of type `IFormFile` with the `[FromForm]` attribute. Remove the attribute from those parameters and everything should work just fine.

They're two different concepts that don't make sense together - they represent two different request binding strategies in ASP.NET Core. While this doesn't cause the API itself to behave incorrectly, it does impact the `ApiDescription` that's surfaced by ASP.NET Core to Swashbuckle. Here's [some additional info from a related issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1183#issuecomment-612022568)

**Comment by christianAtSuddath** [comment]
Nice! Leaving the `[FromForm]` attribute off worked! Thank you for taking the time to respond!
