### ISSUE TITLE
Could not load type 'Swashbuckle.AspNetCore.Swagger.SwaggerDocument' from assembly

### ISSUE THREAD

**Issue by juliopereirab** [domaindrivendev/Swashbuckle.AspNetCore#1863]
At the moment I'm trying to update a project from dotnet 2.1 to 3.1. To do that and avoid exceptions I've had to upgrade swagger, and everything works, except swagger. For some unknown reason Swagger returns this exception when I try to produce it's json mapping. I'm making these changes in a Catalina macOs, macBook Pro. 

     The command "dotnet swagger tofile --output .\autogenerated-api.json bin/Debug/netcoreapp3.1/App.dll v2" exited with code 134.
    ...

     Unhandled exception. System.TypeLoadException: Could not load type 'Swashbuckle.AspNetCore.Swagger.SwaggerDocument' from assembly 'Swashbuckle.AspNetCore.Swagger, Version=5.6.3.0, Culture=neutral, PublicKeyToken=62657d7474907593'.
     at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
     at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
     at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
     at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)

So far I haven't found any information about this exception specifically. What's going wrong?. I'm using latest Swagger along with a pretty plain setting: 

    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="5.6.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="5.6.3" />

    ...

      <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet swagger tofile --output .\autogenerated-api.json $(OutputPath)$(AssemblyName).dll v2" />
  </Target>

And the setting in Startup.cs: 

    services.AddSwaggerGen(c =>
        {
                c.SwaggerDoc("v2", new OpenApiInfo { Title = "App Api", Version = "v2"});
        });

    ...

                if (env.IsDevelopment())
            {
                app.UseSwagger();

                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/v2/swagger.json", $"{nameof(App)} API V2");
                    c.InjectStylesheet("/brand.css");
                });
            }

The idea naturally is to generate a json mapping on every development run. Still wondering why Swagger is trying to reach a package it doesn't have (SwaggerDocument). 

Thanks.

**Comment by vdesplanque** [comment]
Hi,

I'm in the same situation, updating a project from dotnet 2.1 to 3.1 :

```
dotnet swagger tofile --output ../Documentation/v0/swagger.json bin\Debug\netcoreapp3.1\my.dll v0
Unhandled exception. System.TypeLoadException: Could not load type 'Swashbuckle.AspNetCore.Swagger.SwaggerDocument' from assembly 'Swashbuckle.AspNetCore.Swagger, Version=5.6.3.0, Culture=neutral, PublicKeyToken=62657d7474907593'.
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args)
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)
```

@juliopereirab did you find a workaround ?

**Comment by domaindrivendev** [comment]
This could be a conflict between the version of your Cli tool installed on your machine and the version of Swashbuckle in use by your application - they should be the same.

**Comment by domaindrivendev** [comment]
Closing due to inactivity

**Comment by badsyntax** [comment]
Not the op but matching the cli tool version with the version of Swashbuckle used in my app fixed this issue for me.
