### ISSUE TITLE
Classes from different projects with the same name cause Swagger to fail to generate schema

### ISSUE THREAD

**Issue by JacksReacher** [domaindrivendev/Swashbuckle.AspNetCore#1895]
Version 5.6.3.

Issue: Classes from different projects with the same name cause Swagger to fail to generate schema. 
Actual Results:
Can't use schemaId "$TeamMemberAddRequest" for type "$VWAC.AzureSelfServicePortal.DataContracts.TeamMemberAddRequest". The same schemaId is already used for type "$VWAC.AzureSelfServicePortal.Services.Models.TeamMemberAddRequest"

See SwaggerGen.SchemaGenerator.GenerateSchema method.

Expected Results:

Classes from different projects with the same name do NOT cause Swagger to fail to generate schema.

StackTrace:
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.RegisterType(Type type, String schemaId) in C:\Repos\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SchemaRepository.cs:line 25
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(Type type, SchemaRepository schemaRepository, Func`1 definitionFactory) in C:\Repos\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGenerator\SchemaGenerator.cs:line 382
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type type, SchemaRepository schemaRepository) in C:\Repos\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGenerator\SchemaGenerator.cs:line 143
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo) in C:\Repos\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SchemaGenerator\SchemaGenerator.cs:line 32

**Comment by JacksReacher** [comment]
Never mind, found the solution; 

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                c.CustomSchemaIds(i => i.FullName);
            });

**Comment by JacksReacher** [comment]
Never mind, found the solution;

        services.AddSwaggerGen(c =>
        {
            c.SwaggerDoc("v1", new OpenApiInfo
            {
            c.CustomSchemaIds(i => i.FullName);
        });
