### ISSUE TITLE
Swashbuckle CLI Throws Exception for Security Definition Absolute URI

### ISSUE THREAD

**Issue by tameyer1** [domaindrivendev/Swashbuckle.AspNetCore#1949]
I am running 5.6.3 of the CLI in an Azure DevOps step during build to generate a swagger.json file.
In my API startup I have defined the security requirements and a URI to the identity provider.  I need to use an absolute URI so when you run the swagger ui for the API it knows where to get the token (its an external security provider).
```
c.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                {
                    Type = SecuritySchemeType.OAuth2,
                    Flows =new OpenApiOAuthFlows{ 
                        Implicit = new OpenApiOAuthFlow
                        {
                            AuthorizationUrl = new Uri(identityUrl + "/connect/authorize", UriKind.Absolute),
                            Scopes = new Dictionary<string, string> { { "myapi", "access to myapi" } }
                        },
                        ClientCredentials = new OpenApiOAuthFlow
                        {
                            TokenUrl = new Uri(identityUrl + "/connect/token", UriKind.Absolute),
                            Scopes = new Dictionary<string, string> { { "myapi", "access to myapi" } }
                        }
                    },
                    
                });
```

When the CLI runs it throws an exception for the URIs above.

2021-01-11T13:47:23.7603570Z Tool 'swashbuckle.aspnetcore.cli' (version '5.6.3') was successfully installed. Entry is added to the manifest file D:\a\1\s\.config\dotnet-tools.json.
2021-01-11T13:47:29.9084142Z Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
2021-01-11T13:47:29.9085099Z    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
2021-01-11T13:47:29.9085663Z    at System.Uri..ctor(String uriString, UriKind uriKind)
2021-01-11T13:47:29.9086748Z    at MyApi.CustomExtensionsMethods.<>c__DisplayClass2_0.<AddCustomAuthentication>b__1(SwaggerGenOptions c) in D:\a\1\s\MyApi\Startup.cs:line 141
2021-01-11T13:47:29.9087851Z    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
2021-01-11T13:47:29.9088516Z    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
2021-01-11T13:47:29.9089286Z    at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
2021-01-11T13:47:29.9089859Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2021-01-11T13:47:29.9090534Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2021-01-11T13:47:29.9091105Z    at System.Lazy`1.CreateValue()
2021-01-11T13:47:29.9091472Z    at System.Lazy`1.get_Value()
2021-01-11T13:47:29.9092031Z    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
2021-01-11T13:47:29.9092668Z    at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
2021-01-11T13:47:29.9093214Z    at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
2021-01-11T13:47:29.9094091Z    at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions..ctor(IOptions`1 swaggerGenOptionsAccessor, IServiceProvider serviceProvider, IWebHostEnvironment hostingEnvironment)
2021-01-11T13:47:29.9095266Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2021-01-11T13:47:29.9096196Z    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2021-01-11T13:47:29.9097262Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9098299Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9099332Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9102563Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9103592Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9104694Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9105668Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitNoCache(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9106946Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9108004Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9109092Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9110287Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9111321Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9112339Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9113369Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9114653Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
2021-01-11T13:47:29.9115907Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9116939Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9117901Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2021-01-11T13:47:29.9118988Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2021-01-11T13:47:29.9119772Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2021-01-11T13:47:29.9120295Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
2021-01-11T13:47:29.9120808Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2021-01-11T13:47:29.9121317Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2021-01-11T13:47:29.9121807Z    at Microsoft.Extensions.DependencyInjection.SwaggerGenServiceCollectionExtensions.<>c.<AddSwaggerGen>b__0_1(IServiceProvider s)
2021-01-11T13:47:29.9122373Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9123294Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9123863Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9124482Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9125054Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9125714Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9126285Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
2021-01-11T13:47:29.9126871Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2021-01-11T13:47:29.9127408Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2021-01-11T13:47:29.9127985Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
2021-01-11T13:47:29.9128617Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2021-01-11T13:47:29.9129148Z    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
2021-01-11T13:47:29.9129557Z    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2021-01-11T13:47:29.9130036Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2021-01-11T13:47:29.9130542Z    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2021-01-11T13:47:29.9131134Z    at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
2021-01-11T13:47:29.9131848Z    at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
2021-01-11T13:47:29.9132513Z    at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
2021-01-11T13:47:29.9133174Z    at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111

**Comment by tameyer1** [comment]
Answering my own question, though maybe not in the optimal way:

AuthorizationUrl = string.IsNullOrEmpty(identityUrl ) ? 
new Uri("/connect/authorize", UriKind.Relative) :  
new Uri(identityUrl + "/connect/authorize", UriKind.Absolute),

gets me past the error. I could probably also make it absolute to a loclhost so the swagger.json definition is correct
