### ISSUE TITLE
Problem by update from version "5.6.3" to version "6.0.0"

### ISSUE THREAD

**Issue by hhu-mahmoud** [domaindrivendev/Swashbuckle.AspNetCore#1994]
I'm using .Net5.
With version "5.6.3" everything is fine and it works perfectly  but =>
Swagger dose not work after update from version "**5.6.3**" to verion "**6.0.0**" => After analyzation I found that if the the api method has as example FormQuery with template name or such as this code, the it throw an exception:

` 
[HttpGet]
 public IActionResult GetProducts([FromQuery] [SwaggerParameter("Search keywords", Required = true)] string keywords)
 {
  return null;
}
`
or
`
[HttpGet("Challenge")]
public Task<IActionResult> GetChallengeAsync([FromQuery(Name = "challenge")] string challenge)
{
  return default;
}
`

the exception is:
MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,Microsoft.OpenApi.Models.OpenApiSchema> Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.get_Schemas()'.
Swashbuckle.AspNetCore.Filters.RequestExample.SetRequestExampleForOperation(OpenApiOperation operation, SchemaRepository schemaRepository, Type requestType, object example)

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action
MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,Microsoft.OpenApi.Models.OpenApiSchema> Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.get_Schemas()'.
Swashbuckle.AspNetCore.Filters.RequestExample.SetRequestExampleForOperation(OpenApiOperation operation, SchemaRepository schemaRepository, Type requestType, object example)
Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.SetRequestExamples(OpenApiOperation operation, OperationFilterContext context)
Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)

System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,Microsoft.OpenApi.Models.OpenApiSchema> Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.get_Schemas()'.
   at Swashbuckle.AspNetCore.Filters.RequestExample.SetRequestExampleForOperation(OpenApiOperation operation, SchemaRepository schemaRepository, Type requestType, Object example)
   at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.SetRequestExamples(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   
SwaggerGeneratorException: Failed to generate Operation for action See inner exception 

Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable<ApiDescription> apiDescriptions, SchemaRepository schemaRepository)
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(string documentName, string host, string basePath)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

---> System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,Microsoft.OpenApi.Models.OpenApiSchema> Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.get_Schemas()'.
   at Swashbuckle.AspNetCore.Filters.RequestExample.SetRequestExampleForOperation(OpenApiOperation operation, SchemaRepository schemaRepository, Type requestType, Object example)
   at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.SetRequestExamples(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.Filters.ServiceProviderExamplesOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by domaindrivendev** [comment]
@hhu-mahmoud could you please create a minimal app (i.e. starting from empty project) that repro's the issue and post to github so I can pull down and troubleshoot?

**Comment by effyteva** [comment]
We receive the same error, tracking this

**Comment by hhu-mahmoud** [comment]
@domaindrivendev @effyteva 

While I'm creating a new test project to discover where is the problem, I found, that when I add the "ExampleFilter" under "AddSwaggerGen", then it dose not work with the new version >= 6.0.0 for the 2 Packages ("Swashbuckle.AspNetCore" and "Swashbuckle.AspNetCore.Newtonsoft") ... if you want to run the project without problem, then you should "comment" `c.ExampleFilters();` then it will work but you will lose the examples.

I create for you the test project and it works now with example filters with the old version "5.6.3" .. try to update the 2 Packages ("Swashbuckle.AspNetCore" and "Swashbuckle.AspNetCore.Newtonsoft") then you will see the exception, because of the "ExampleFilters".

The link of the test project is: [https://github.com/hhu-mahmoud/swagger](https://github.com/hhu-mahmoud/swagger)

**Comment by domaindrivendev** [comment]
Unfortunately, the following commit - 993fb8540e234a7ee52ef81c4ba2424e800be7e3, inadvertantly introduced a breaking change by modifying (albeit subtly) the `SchemaRepository.Schemas` signature.

I've reverted that changed and push out a `6.0.2` hotfix, if you pull that down you're issue should be resolved.

**Comment by hhu-mahmoud** [comment]
@domaindrivendev Thanks for the hotfix. The issue is now resolved and it works again.

**Comment by effyteva** [comment]
Thanks for the fix @domaindrivendev, this resolved the issue.
I've opened another issue when migrating to the new 6.0.2 release #1996.
Keep up the great work!

Effy
