### ISSUE TITLE
Error generating schema containing TimeSpans when UseAllOfForInheritance option is enabled

### ISSUE THREAD

**Issue by Numpsy** [domaindrivendev/Swashbuckle.AspNetCore#2090]
Hi,

I tried plugging Swashbuckle.AspNetCore (6.1.2) into an existing ASP.Net Core 3.1 web api project and it was generating the schema ok with default options, but then when I enabled the ```UseAllOfForInheritance``` option I started seeing exceptions thrown during schema generation.

I tried it with a new project and if I have this simple controller setup

```csharp
    public class TSResult
    {
        public TimeSpan time { get; set; }
    }

    [ApiController]
    [Route("[controller]")]
    public class TimeController : ControllerBase
    {
        [HttpGet]
        public TSResult Get()
        {
            return new TSResult();
        }
    }
```

with just this is the Swashbuckle setup:

```csharp
    services.AddSwaggerGen(c =>
    {
        c.UseAllOfForInheritance();
    });
```

Then I get this exception when it tries to generate the schema:
```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - SwashbuckleTimespan.Controllers.TimeController.Get (SwashbuckleTimespan). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - SwashbuckleTimespan.Controllers.TSResult. See inner exception
 ---> System.InvalidOperationException: Can't use schemaId "$<StandardName>e__FixedBuffer" for type "$Interop+Kernel32+TIME_ZONE_INFORMATION+<StandardName>e__FixedBuffer". The same schemaId is already used for type "$Interop+Kernel32+TIME_DYNAMIC_ZONE_INFORMATION+<StandardName>e__FixedBuffer"
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.RegisterType(Type type, String schemaId)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo)
```

I see other issues about tweaking names or schema id mappings in order to avoid clashes, but I have no idea where ```$Interop+Kernel32+TIME_DYNAMIC_ZONE_INFORMATION+<StandardName>e__FixedBuffer``` is coming from in the first place?

Any ideas?

Thanks.

**Comment by domaindrivendev** [comment]
@Numpsy would you mind creating a minimal app (i.e. starting from empty project) that repro's the issue and post to github so I can pull down and troubleshoot?

**Comment by Numpsy** [comment]
Hi,

Will https://github.com/Numpsy/SwashbuckleTimeTest do?

That project has ```OpenApiGenerateDocumentsOnBuild``` enabled in the csproj file, and when I try to build it, it fails with the above error. Without that setting it build ok, but then gets the same error if I go to the /swagger endpoint on the running service.

Thanks

**Comment by domaindrivendev** [comment]
I've iterated many times on the polymorphism/inheritance behavior and it turns out to be extremely difficult to get right. I knew the current implementation was complex but felt it was somewhat resilient - however your issue has highlighted that it's still quite brittle. The biggest difficulty is around detecting which inheritance hierarchies in your code base should and shouldn't be surfaced in the generated OpenAPI document. For example, it makes sense to surface high level hierachies like `DigitalProduct <= Product`, but it doesn't make sense to surface a low level hierachy like `System.TimeSpan <= System.ValueType`, and actually it's the latter that's resulting in an overeager extrapolation of low-level (and problematic) type hierarchies and causing your issue.

This area of the code needs a major rethink and refactor, and so in the meantime, I would recommend using the annotations library to be explicit about which type hierarchies in your code base are surfaced to the API docs. See the following readme section for more details:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#list-known-subtypes-for-inheritance-and-polymorphism

**Comment by Numpsy** [comment]
Thanks, being explicit about it is ok (there aren't very many things that actually need inheritance or would need to be annotated).

**Comment by HazyFish** [comment]
`UseOneOfForPolymorphism` also cause the same problem in my .NET 7 project.
