### ISSUE TITLE
If the JSON string contains bool value, using OpenApiAnyFactory.CreateFromJson() will get null in this field.

### ISSUE THREAD

**Issue by djjsdtc** [domaindrivendev/Swashbuckle.AspNetCore#2091]
I was creating an example of my model using OpenApiAnyFactory.CreateFromJson(string). When the JSON contains bool value (true/false), I found the output example's field is filled by "null".

Example:
Expected: { "TestValue": true }
Actual result: { "TestValue": null }

Example 2:
```csharp
class Program
{
    static void Main(string[] args)
    {
        var testObj = new Test {TestValue = true};
        var openApiObj = OpenApiAnyFactory.CreateFromJson(JsonSerializer.Serialize(testObj)) as OpenApiObject;
        Console.WriteLine(openApiObj["TestValue"] == null);
        // Should be false, but actual output is true
    }
}

class Test
{
    public bool TestValue { get; set; }
}
```

I looked into the code of OpenApiAnyFactory.CreateFromJson(string). I found when converting bool values in an object, an exception is thrown and catched, like this:
```
System.Text.Json.JsonException: 'T' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'T' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Swashbuckle.AspNetCore.SwaggerGen.CreateFromJson(String json)
```

The reason is, when passing a bool value into CreateOpenApiObject(JsonElement) method, its valueAsJson value will be "True" or "False" (not "true" or "false", because of true.ToString()/false.ToString()), then the JsonSerializer.Deserialize method throws this exception.

**Comment by domaindrivendev** [comment]
Will be available in `6.1.3`, which is being pushed now
