### ISSUE TITLE
.NET 6 minimal APIs and the Swashbuckle CLI

### ISSUE THREAD

**Issue by bradygaster** [domaindrivendev/Swashbuckle.AspNetCore#2145]
We were doing some experimenting building a new API using the .NET 6 minimal web template. So far, Swashbuckle is working as expected. However. we noticed one bug in which the CLI fails Here's some code for the new minimal api:

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Collections.Generic;
using System.Linq;

const string OpenApiDocumentName = "v1";
const string MemcacheKey = "items";
const string Greeting = "Hello {0}!";

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddMemoryCache();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options => options.SwaggerDoc(OpenApiDocumentName, new OpenApiInfo
{
    Title = "Minimal Swagger Test",
    Description = "Simple description",
    Version = "v1"
}));

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseSwagger(setup => setup.SerializeAsV2 = true);

app.Services.GetService<IMemoryCache>().Set<List<TheApiModel>>(MemcacheKey, new List<TheApiModel>());

app.MapGet("/", (IMemoryCache memcache) =>
    memcache.Get<List<TheApiModel>>(MemcacheKey)
);

app.MapGet("/{target}", (string target,IMemoryCache memcache) =>
    memcache.Get<List<TheApiModel>>(MemcacheKey).FirstOrDefault(_ => _.Target == target)
);

app.MapPost("/create", (TheApiModel model, IMemoryCache memcache) =>
{
    var existing = memcache.Get<List<TheApiModel>>(MemcacheKey);
    existing.Add(model);
    memcache.Set<List<TheApiModel>>(MemcacheKey, existing);
    return string.Format(Greeting, model.Target);
});

app.MapGet("/version", () => typeof(Microsoft.AspNetCore.Http.RequestDelegateFactory)
    .Assembly.GetCustomAttributes(true)
        .OfType<System.Reflection.AssemblyInformationalVersionAttribute>().First().InformationalVersion
    );

app.UseSwaggerUI();

app.Run();

public record TheApiModel(string Target = "World");
```

This is built in a project here: https://github.com/bradygaster/minimalApiWithSwagger

We noticed that when using the CLI, no OpenAPI file is output and we see an error. When I execute the global tool locally:

```
swagger tofile --output swagger.json --serializeasv2 .\minimalWeb.dll v1
```

Here's the output i'm seeing:

```
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'minimalWeb'.
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName) in Microsoft.AspNetCore.Hosting.dll:token 0x600013e+0x14c
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors) in Microsoft.AspNetCore.Hosting.dll:token 0x6000191+0x2d4
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_2.<BuildCommonServices>b__5(IServiceProvider _) in Microsoft.AspNetCore.Hosting.dll:token 0x6000289+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) in Microsoft.Extensions.DependencyInjection.dll:token 0x60000a8+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context) in Microsoft.Extensions.DependencyInjection.dll:token 0x600008e+0x61
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) in Microsoft.Extensions.DependencyInjection.dll:token 0x60000a7+0x4e
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000069+0x38
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in System.Collections.Concurrent.dll:token 0x60000d3+0x4f
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000067+0xd
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000062+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider) in Microsoft.Extensions.DependencyInjection.Abstractions.dll:token 0x6000094+0xe
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup() in Microsoft.AspNetCore.Hosting.dll:token 0x6000153+0x9
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices() in Microsoft.AspNetCore.Hosting.dll:token 0x6000152+0x8
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize() in Microsoft.AspNetCore.Hosting.dll:token 0x600014f+0x0
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build() in Microsoft.AspNetCore.Hosting.dll:token 0x6000190+0x9b
   at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 133
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
```

**Comment by bradygaster** [comment]
cc @davidfowl and @pranavkm

**Comment by davidfowl** [comment]
Hey @domaindrivendev, we have a helper that encapsulates logic for resolving the service provider from an assembly for these types of applications, see https://github.com/dotnet/runtime/blob/7833828914a42f8c99dfa6f18ccd47f99dc2b56e/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs#L107. You should be able to use this package (it's shared source only) in your project (I can send a PR if you want) to support these new patterns. Alternatively, we can copy the logic (though I would recommend not doing that).

**Comment by domaindrivendev** [comment]
@davidfowl a PR would be great I’ll keep an eye out for it 👍

**Comment by davidfowl** [comment]
@domaindrivendev I sent a PR. Let me know what you think!

**Comment by bradygaster** [comment]
I can confirm from the preview build that this worked. CC @phil-allen-msft as i also let him know that this worked when I tried it via the command line, but when i installed it and tried it within vs during publishing it seems to have defaulted to the public one again. if there's a way to force it to use the preview let me know.

**Comment by red8888** [comment]
Has this been released? I get the same error with .NET 6 when running the latest version (6.2.3.0) of the cli

**Comment by davidfowl** [comment]
Yes, update all of your packages. Show us your csproj.
