### ISSUE TITLE
System.ArgumentOutOfRangeException: Count cannot be less than zero. (Parameter 'count')

### ISSUE THREAD

**Issue by thokl71** [domaindrivendev/Swashbuckle.AspNetCore#2245]
I have a route with double points (e.g. /api/v1/bill:confirm)
after updating from 6.2.1 to 6.2.2 the swagger.json file cannot be created anymore.
I get:
An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: Count cannot be less than zero. (Parameter 'count')
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiDescriptionExtensions.RelativePathSansParameterConstraints(ApiDescription apiDescription)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c.<GeneratePaths>b__6_0(ApiDescription apiDesc)
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by MvdZwart** [comment]
You could try to work around it by replacing the semilocon with an slash:
/api/v1/bill:confirm becomes /api/v1/bill/confirm. That would work for sure.

You could also try to replace the semilocon with a period:
/api/v1/bill:confirm becomes /api/v1/bill.confirm

I haven't tested the latter.
