### ISSUE TITLE
Potential problems with 6.3.0

### ISSUE THREAD

**Issue by esbenUnipluss** [domaindrivendev/Swashbuckle.AspNetCore#2368]
Running a .net 6.0 C# Web API.

After upgrading Swashbuckle.AspNetCore  from 6.2.3 to 6.3.0,
the API will not start, and gives the following error message:

>  Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action(ActionName) . See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type(ActionType). See inner exception
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateArraySchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__1()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.<>c__DisplayClass10_0.<GenerateConcreteSchema>b__3()
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateResponseMediaType(ModelMetadata modelMetadata, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.<>c__DisplayClass19_0.<GenerateResponse>b__2(String contentType)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponse(ApiDescription apiDescription, SchemaRepository schemaRepository, String statusCode, ApiResponseType apiResponseType)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateResponses(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)a
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

 by downgrading back to 6.2.3 it started working again.

I also have the Swashbuckle.AspNetCore.Newtonsoft installed - but any permutation of version 6.3.0 gives the same error message.

**Comment by domaindrivendev** [comment]
Thx for reporting this. Could you create an app (ideally as simple as possible) that repro’s the issue and post to GitHub. That way, I can pull down and it will be much easier to troubleshoot

**Comment by nielswitte** [comment]
Facing the same issue after upgrading from Swashbuckle.AspNetCore 6.2.3 to version 6.3.0. Also using Newtonsoft. 

6.2.3 works fine.

**Comment by zsalkus** [comment]
@domaindrivendev adding link to the app which reproduces the issue. it is caused by builder.Services.AddSwaggerGenNewtonsoftSupport() (l:6) in Program.cs due to enum in CrashObject.cs

https://github.com/zsalkus/Swashbuckle.AspNetCore.CrashDemo

**Comment by KnightSwordAG** [comment]
I am having the same issue with an API I also updated, but I'm not using Newtonsoft. Here's my error:
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'Microsoft.OpenApi.Models.OpenApiSchema Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator.GenerateSchema(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, System.Reflection.MemberInfo, System.Reflection.ParameterInfo)'.
   at SignalRSwaggerGen.SignalRSwaggerGen.GetOpenApiSchema(DocumentFilterContext context, Type type)
   at SignalRSwaggerGen.SignalRSwaggerGen.<>c__DisplayClass8_0.<ToOpenApiParameters>b__0(ParameterInfo param)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at SignalRSwaggerGen.SignalRSwaggerGen.AddOpenApiPath(OpenApiDocument swaggerDoc, DocumentFilterContext context, SignalRHubAttribute hubAttribute, String tag, String methodPath, Operation operation, String summary, String description, IEnumerable`1 methodParams, ParameterInfo methodReturnParam, MethodInfo method, MemberElement methodXml)
   at SignalRSwaggerGen.SignalRSwaggerGen.ProcessMethod(OpenApiDocument swaggerDoc, DocumentFilterContext context, SignalRHubAttribute hubAttribute, String hubPath, String tag, MethodInfo method, MemberElement methodXml)
   at SignalRSwaggerGen.SignalRSwaggerGen.ProcessHub(OpenApiDocument swaggerDoc, DocumentFilterContext context, Type hub, XmlComments xmlComments)
   at SignalRSwaggerGen.SignalRSwaggerGen.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I'm still investigating a cause, but the issue is ONLY from upgrading from 6.2.3 to 6.3.0.

**Comment by KnightSwordAG** [comment]
> 
Okay, can confirm, this is unrelated. I can confirm that the issue is due to the SignalRSwaggerGen package. It doesn't play nice with the new Swashbuckle update. This is a red herring.

**Comment by manandre** [comment]
Same issue here with a `Dictionary<TEnum, string>`.
The regression has been introduced in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2166

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/d63f028b6325857bd7a33a0dd7fc12fadb5c4e74/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L91-L94

When the Keys of the dictionary are known, the `schema.AdditionalPropertiesAllowed` is `false` and then `schema.AdditionalProperties` is `null`, what indeed generates the NRE.

@Eneuman Can you please take a look at this specific case?

**Comment by Eneuman** [comment]
I'll take a look at this right away make a PR for it.

**Comment by Eneuman** [comment]
> > 
> 
> Okay, can confirm, this is unrelated. I can confirm that the issue is due to the SignalRSwaggerGen package. It doesn't play nice with the new Swashbuckle update. This is a red herring.

It looks like that package is using dictionary with known keys so this might be related to this. 
`SignalRSwaggerGen.<>c__DisplayClass8_0.<ToOpenApiParameters>b__0`

**Comment by DaniinXorchenabo** [comment]
So, version 6.3.1 fixed it and exception not throwed, But swagger scheme not display this key as enum:

simple enum:
![image](https://user-images.githubusercontent.com/45897837/170119672-0480335c-7cfc-46a6-8f94-4c5241f81f87.png)

Dictionary<Enum, some>
![image](https://user-images.githubusercontent.com/45897837/170120119-d001e5ca-b6e7-4c45-8add-90b91c3c25a1.png)

May be can you like that?
![image](https://user-images.githubusercontent.com/45897837/170120983-3fb5f31c-4656-4de7-a0ca-b44766e9252d.png)

thanks

**Comment by FrankSzendzielarz** [comment]
Similar error. Where are the swagger pdb files for debugging?

**Comment by zendu** [comment]
I am facing the same problem in v6.4.0.

**Comment by black-byte** [comment]
Is there any workaround at the moment for this issue?

**Comment by plutora-steve-g** [comment]
A workaround is to compile your own version. @domaindrivendev can we address this issue next release please?

**Comment by coonmoo** [comment]
We are facing the same issue. Not able to update from 6.2.3 (last working version)

**Comment by milosloub** [comment]
Same issue here. We have to revert our project to 6.2.3 version

**Comment by vanjar** [comment]
Also same problems here. Revert to 6.2.3 version was needed

**Comment by sergei-lobanov** [comment]
Hey, there is a blocker issue for most of the users and no solution? Any plans to fix it soon?

**Comment by rutemja** [comment]
@Eneuman @domaindrivendev Could someone please re-open this issue? We ran into it today as well and needed to downgrade again. Thanks :)
