### ISSUE TITLE
Method not found: 'Microsoft.OpenApi. Models.OpenApiSchema Swashbuckle. AspNetCore.SwaggerGen. IschemaGenerator.GenerateSchema in version 6.4.0

### ISSUE THREAD

**Issue by shrutigithub** [domaindrivendev/Swashbuckle.AspNetCore#2465]
After Upgrading to swagger version 6.4.0 , we are getting error:
Method not found: 'Microsoft.OpenApi. Models.OpenApiSchema Swashbuckle. AspNetCore.SwaggerGen. IschemaGenerator.GenerateSchema

Detailed Stack trace:
See inner exception ---> Swashbuckle. AspNetCore.SwaggerGen. SwaggerGeneratorException: Failed to generate schema for type - System.String. See inner exception ---> System. MissingMethodException: Method not found: 'Microsoft.OpenApi. Models.OpenApiSchema Swashbuckle. AspNetCore.SwaggerGen. IschemaGenerator.GenerateSchema (Sys tem. Type, Swashbuckle.AspNetCore.SwaggerGen. SchemaRepository, System.Reflection. MemberInfo, System.Reflection. ParameterInfo)'.
at Microsoft.Azure.Global.Services. Common. Service.OpenApi.SchemaFilters. SubTypeOfFilter.Apply(OpenApiSchema schema, SchemaFilterContext context)
at Swashbuckle. AspNetCore.SwaggerGen. SchemaGenerator.ApplyFilters (OpenApiSchema schema, Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, Para meterInfo parameterInfo)
at Swashbuckle. AspNetCore.SwaggerGen. SchemaGenerator.GenerateSchemaForType (Type modelType, SchemaRepository schemaRepository)
at Swashbuckle. AspNetCore.SwaggerGen. SchemaGenerator.GenerateSchema (Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo param eterInfo, ApiParameter RouteInfo routeInfo)
at Swashbuckle. AspNetCore.SwaggerGen. SwaggerGenerator.GenerateSchema (Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo param eterInfo, ApiParameter RouteInfo routeInfo)
--- End of inner exception stack trace ---
at Swashbuckle. AspNetCore.SwaggerGen. SwaggerGenerator.GenerateSchema (Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo param eterInfo, ApiParameter RouteInfo routeInfo)
at Swashbuckle. AspNetCore.SwaggerGen. SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository)

Also , we tried upgrading to 5.6.0, we get the issue:

Unhandled exception. System.MissingMethodException: Method not found: 'Boolean Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.TryGetIdFor(System.Type, System.String ByRef)'.
 at Microsoft.Azure.Global.Services.Common.Service.OpenApi.DocumentFilters.PolymorphismDocumentFilter.RegisterSubClasses(SchemaRepository schemaRegistry, ISchemaGenerator schemaGenerator, Type abstractType)
 at Microsoft.Azure.Global.Services.Common.Service.OpenApi.DocumentFilters.PolymorphismDocumentFilter.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
 at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
 at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 72
 at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
 at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
 at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111

**Comment by shrutigithub** [comment]
@domaindrivendev Please suggest a workaround. We need to fix this as soon as possible. Unable to upgrade to any swagger version after 5.5

**Comment by shrutigithub** [comment]
Steps to replicate the issue:
1. Upgraded the swagger version in 2 files:
1.1. dotnet-tools.json file inside .config folder of our project : {"version":1,"isRoot":true,"tools":{"swashbuckle.aspnetcore.cli":{"version":"6.2.3","commands":["swagger"]}}}
1.2. Package.props file : <PackageReference Update="Swashbuckle.AspNetCore" Version="6.2.3" />
2. ran commad : 
dotnet swagger tofile  --output <destination>/swagger.json --serializeasv2 <dll file> 1.0

**Comment by corfor** [comment]
downgrading to previous version 6.3.1 resolved it for me.

**Comment by Aiiida** [comment]
This seems to work https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2369#issuecomment-1123025347

**Comment by martincostello** [comment]
#2801 would guard against unintended breaking changes in the future.
