### ISSUE TITLE
Classes/enums with same names break type registration

### ISSUE THREAD

**Issue by IvMisticos** [domaindrivendev/Swashbuckle.AspNetCore#2482]
I am using v6.4.0

In my case I have two enums with the same name:
```cs
public class Request1 {
    public enum VType {
        Name,
        Email
    }
}

public class Request2 {
    public enum VType {
        Name,
        Id
    }
}
```

If I try to open the swagger / generate schema, it will produce the following error:
```cs
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Redacted (Redacted). See inner exception
       ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - Redacted.Request2+VType. See inner exception
       ---> System.InvalidOperationException: Can't use schemaId "$VType" for type "$Request2+VType". The same schemaId is already used for type "$Request1+VType"
         at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.RegisterType(Type type, String schemaId)
         at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
         at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
         at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchema(Type type, SchemaRepository schemaRepository, PropertyInfo propertyInfo, ParameterInfo parameterInfo, ApiParameterRouteInfo routeInfo)
```

**Comment by icnocop** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1431
