### ISSUE TITLE
SwaggerGeneratorException: Conflicting method/path combination when having 2 controllers with same method name but different route.

### ISSUE THREAD

**Issue by motz-art** [domaindrivendev/Swashbuckle.AspNetCore#2543]
When 2 controllers one OData and the other normal web api controller with same name but from different namespaces contain 2 methods with same name SwaggerGeneratorException is thrown even so controllers are mapped to different routes.

## Steps to reproduce

1. Create 2 controllers named `NotesController` with `Get` method in 2 different namespaces:
One is derived from `ODataController`
``` C#
namespace ODataTutorial.Controllers.OData;

public class NotesController : ODataController
{
    [EnableQuery()]
    public IQueryable<Note> Get()
    {
        // Some code here...
    }
}
```
and another derived from `ControllerBase`
``` C#
namespace ODataTutorial.Controllers;

[Route("api/[controller]")]
[ApiController]
public class NotesController : ControllerBase
{
    [HttpGet]
    public async Task<IActionResult> Get()
    {
        // Some code here...
    }
}
```

**Note**: Controllers' names should be the same, as well as both controller should have method with same name (`Get` in my case).

**Note2**: This works fine for 2 controllers inherited from `ControllerBase`.

in `program.cs` setup like so:
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers().AddOData(opt => opt.AddRouteComponents("v1", GetEdmModel()).Filter().Select().Expand());
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new() { Title = "ODataTutorial", Version = "v1" });
});

var app = builder.Build();

app.UseSwagger();

app.MapControllers();

app.Run();
```

2. Run application and navigate to `/swagger/v1/swagger.json`

**Expected**:
Manifest is shown,

**Actual**:
Exception is thrown
```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination "GET v1/Notes" for actions - ODataTutorial.Controllers.NotesController.Get (ODataTutorial),ODataTutorial.Controllers.OData.NotesController.Get (ODataTutorial). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Packages Version
``` csproj
<TargetFramework>net6.0</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.11" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
```

## Repository with reproduction
full steps to reproduce you can find here: https://github.com/motz-art/SwaggerBugReport

**Comment by domaindrivendev** [comment]
Dup of #2035
