### ISSUE TITLE
CLI 6.4.0 -- tofile randomly fails on Microsoft.Identity packages -- .NET 6

### ISSUE THREAD

**Issue by QuickScoP3s** [domaindrivendev/Swashbuckle.AspNetCore#2580]
This is our situation:
We're installing and using the CLI tool in an Azure DevOps pipeline to generate a swagger.json file.

For some reason, the `tofile` command randomly fails, and always with an error similar to this:
```
File name: 'Microsoft.IdentityModel.Logging, Version=6.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Identity.Web.MicrosoftIdentityBaseAuthenticationBuilder..ctor(IServiceCollection services, IConfigurationSection configurationSection)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilder..ctor(IServiceCollection services, String jwtBearerAuthenticationScheme, Action`1 configureJwtBearerOptions, Action`1 configureMicrosoftIdentityOptions, IConfigurationSection configurationSection)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderWithConfiguration..ctor(IServiceCollection services, String jwtBearerAuthenticationScheme, Action`1 configureJwtBearerOptions, Action`1 configureMicrosoftIdentityOptions, IConfigurationSection configurationSection)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.AddMicrosoftIdentityWebApi(AuthenticationBuilder builder, IConfigurationSection configurationSection, String jwtBearerScheme, Boolean subscribeToJwtBearerMiddlewareDiagnosticsEvents)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiAuthenticationBuilderExtensions.AddMicrosoftIdentityWebApi(AuthenticationBuilder builder, IConfiguration configuration, String configSectionName, String jwtBearerScheme, Boolean subscribeToJwtBearerMiddlewareDiagnosticsEvents)
   at Microsoft.Identity.Web.MicrosoftIdentityWebApiServiceCollectionExtensions.AddMicrosoftIdentityWebApiAuthentication(IServiceCollection services, IConfiguration configuration, String configSectionName, String jwtBearerScheme, Boolean subscribeToJwtBearerMiddlewareDiagnosticsEvents)
   at Finvictum.API.ServiceCollectionExtensions.AddAppAuthentication(IServiceCollection services, IConfiguration config) in /home/vsts/work/1/s/Finvictum.API/ServiceCollectionExtensions.cs:line 60
   at Program.<<Main>$>g__CreateApplication|0_0(String[] args) in /home/vsts/work/1/s/Finvictum.API/Program.cs:line 55
   at Program.<Main>$(String[] args) in /home/vsts/work/1/s/Finvictum.API/Program.cs:line 32
```

As you can see in the StackTrace, the error points to this line in our code:
```cs
public static IServiceCollection AddAppAuthentication(this IServiceCollection services, IConfiguration config)
{
    services.AddMicrosoftIdentityWebApiAuthentication(config, "AzureB2C");

    ...
}
```

However, even when I remove that line, we have some other setup pointing to the `IdentityModel` packages and it will fail there...

I've logged all packages after a restore from the pipeline:
![image](https://user-images.githubusercontent.com/12516179/209857871-2015f147-ddcc-4755-b569-300541a8bf1f.png)

---

The strange thing is: Sometimes it works instantly, most of the time we have to run it at least 3 times and in some rare occasions, we had to run it ~10 times

We've tried to reproduce it locally, but it never fails... We can generate the file without fail.

This is the pipeline task:
```yaml
- task: Bash@3
    displayName: 'Generate OpenAPI document'
    inputs:
      targetType: 'inline'
      script: |
        dotnet new tool-manifest --force
        cd output
        dotnet tool install swashbuckle.aspnetcore.cli --version 6.4.0
        export ASPNETCORE_ENVIRONMENT=SWAGGERBUILD
        dotnet swagger tofile --output $(Build.ArtifactStagingDirectory)/swagger.json Finvictum.API.dll v1
```

Some context: We build the project using the `DotNetCoreCLI@2` task and output to the `./output` folder

---

Initially I thought it had to do with this issue: #2355 
Since it would spit out the same error, though that's not the cause, since we're using version 6.4.0 which has a timeout of 30s...

What I did see: When the pipeline task takes longer than 5 seconds, it will fail consistenly
If it takes 5s or less, it will succeed
![image](https://user-images.githubusercontent.com/12516179/209858692-9b152bef-d586-4134-b2ae-ca7f7f911a96.png)
![image](https://user-images.githubusercontent.com/12516179/209858715-edfab4e9-0586-48a1-bca7-c03281e1d91e.png)

Any idea what might be happening?
Or how we can debug the issue?

**Comment by Havunen** [comment]
If you can move to .net8 you could try out if DotSwasbuckle solves this issue, if not I'm interested fixing it

**Comment by martincostello** [comment]
This looks like it's caused by mismatching dependency versions outside of our control.
