### ISSUE TITLE
SwaggerCLI 6.5.0 dotnet swagger tofile command fails with Could not load file or assembly 'Microsoft.OpenApi, Version=1.2.3.0 error for .Net 6 project

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [domaindrivendev/Swashbuckle.AspNetCore#2651]
I am trying to integrate SwaggerCLI to generate OpenAPI documentation at build time for CICD. Project targets .NET 6 framework. I tried using both SwaggerCLI 6.5.0 and 6.2.3 (with corresponding versions of Swashbuckle.AspnetCore) and all runs fail with error. Is there any known compatibility issue between .Net 6 and Swagger CLI?

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.OpenApi, Version=1.2.3.0, Culture=neutral, PublicKeyToken=3f5743946376f042'. The system cannot find the file specified.
File name: 'Microsoft.OpenApi, Version=1.2.3.0, Culture=neutral, PublicKeyToken=3f5743946376f042'
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
```

**Comment by SoujanyaMangipudi** [comment]
@domaindrivendev this is turning out to be a blocking issue for us. Do you have any suggestions here?

**Comment by woeterman94** [comment]
For .NET 6 use  SwaggerCLI 6.4.0

**Comment by martincostello** [comment]
Could you provide some further information about how exactly you're running the tool? I would expect that you'd be running it from where it gets installed to, where all its dependencies would be present in the same directory.
