### ISSUE TITLE
Give a better error with Swashbuckle.AspNetCore.Cli when there is .dll version mismatch

### ISSUE THREAD

**Issue by mcraiha** [domaindrivendev/Swashbuckle.AspNetCore#2666]
If one uses dotnet tool to install Swashbuckle.AspNetCore.Cli and the actual project uses different version of Swashbuckle.AspNetCore.Swagger.dll (e.g. 6.5.0 vs 6.4.0) you will get error like 

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger, Version=6.0.7.0, Culture=neutral, PublicKeyToken=62657d7474907593'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Swashbuckle.AspNetCore.Swagger, Version=6.0.7.0, Culture=neutral, PublicKeyToken=62657d7474907593'
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary`2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 111
```

but it would be better to tell the use that there is a version mismatch. 

So something like:
> Swashbuckle.AspNetCore.Cli version 6.5.0 cannot process %path%/Swashbuckle.AspNetCore.Swagger.dll because it is based on version 6.4.0 and both versions must match!

**Comment by martincostello** [comment]
You could suggest that _any_ tool write custom exception messages to handle mismatched dependency versions in any combination.

This isn't worth us maintaining custom support for.
