### ISSUE TITLE
Bug: Ambiguous Error when using put and post in same webapi controller

### ISSUE THREAD

**Issue by aloksharma1** [domaindrivendev/Swashbuckle.AspNetCore#2729]
Bug Report

Project: Swashbuckle.AspNetCore
Version: 6.5.0
Type: Bug
Reproducible: Yes
Steps to Reproduce:

Create a new ASP.NET Core Web API project.
Install the Swashbuckle.AspNetCore NuGet package.
Create a controller with the following methods:

```
[Route("api/[controller]")]
public class FilesController : ControllerBase
{
    [HttpPost]
    public async Task<IActionResult> Post([FromForm] FileDTO files)
    {
        // ...
    }

    [HttpPut("put")]
    public async Task<IActionResult> Put([FromBody] FileDTO files)
    {
        // ...
    }
}
```
if i change `[FromForm] to [FromBody]` the ui starts working but that's not what i want. i have confirmed this with multiple variations, adding specific routes inside like `[HttpPut("put")]` doesnt solve the issue, neither adding `[SwaggerOperation("UpdateFiles")]`.
if there is any workaround available, do let me know.

StackTrace:

```
An unhandled exception has occurred while executing the request.
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - UnlimitedTravelSources.AssetsManager.Areas.FilesManager.Controllers.FilesController.Post (UnlimitedTravelSources.AssetsManager). See inner exception
 ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiParameterDescriptionExtensions.PropertyInfo(ApiParameterDescription apiParameter)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateSchemaFromFormParameters(IEnumerable`1 formParameters, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBodyFromFormParameters(ApiDescription apiDescription, SchemaRepository schemaRepository, IEnumerable`1 formParameters)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateRequestBody(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by Havunen** [comment]
Can you show your FileDTO  implementation please, does it have properties with identical name ( case insensitive )?

**Comment by martincostello** [comment]
Looks like the exception comes from here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L524

Which in turn, comes from here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/ApiParameterDescriptionExtensions.cs#L60-L67

Feels like _something_ somewhere isn't filtering something enough (or being specific enough), so reflection can't find a single property of the given name.

We'd need to see a bit more information, like what the DTOs look like, to look into this further.
