### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'CONNECT' was not present in the dictionary. 

### ISSUE THREAD

**Issue by voroninp** [domaindrivendev/Swashbuckle.AspNetCore#2740]
I want to create a WebSocket endpoint.
If I use just `[Route]` attribute, Swagger throws an error.

Currently [ASP.NET does not provide `[HttpConnect]` attribute.](https://github.com/dotnet/aspnetcore/issues/52380), so I had to declare it myself:

```
public sealed class HttpConnectAttribute : HttpMethodAttribute
{
    private static readonly string[] _httpMethods = ["CONNECT"];

    public HttpConnectAttribute() : base(_httpMethods)
    {
    }

    public HttpConnectAttribute(string template) : base(_httpMethods, template)
    {
    }
}
```

And after I applied it to the method, swagger throws:
```
System.Collections.Generic.KeyNotFoundException: The given key 'CONNECT' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

I had to exclude that endpoint from the docs: `[ApiExplorerSettings(IgnoreApi = true)]`

1. How do I add support for 'CONNECT' to Swagger docs?
2. Is there any WebSocket support at all?

**Comment by martincostello** [comment]
Looks like we just need to update this dictionary (and make it not throw if there's a custom method or some future other one we've missed added):

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/830c5a6f7468bce6b716d84c034a258dbbcbfe98/src/Swashbuckle.AspNetCore.SwaggerGen/SwaggerGenerator/SwaggerGenerator.cs#L608-L618

**Comment by martincostello** [comment]
See #2600 for supporting CONNECT and other custom HTTP methods.
