### ISSUE TITLE
[Bug]: Incorrect error message when throwing InvalidOperationException in Program.cs

### ISSUE THREAD

**Issue by ahl-trifork** [domaindrivendev/Swashbuckle.AspNetCore#2902]
### Describe the bug

When throwing an `InvalidOperationException` in the Program.cs you get the following error message:
`Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'Backend'.`

This is misleading, as the Startup type was acually found, while something else crashed the application.
If instead you just throw an `Exceptoin` you get the actual error message specified. In my case:
`Unhandled exception. System.Exception: 'ConnectionString' not found in section 'Storage'`

### Expected behavior

To not overwrite the given error message when throwing an `InvalidOperationException`.

If possible, it would be nice to have an indication if an Exception was originally thrown by the user API, or Swashbuckle. That would have made debugging a lot easier. 

### Steps to reproduce

1. Download and unzip attached C# project [test.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/15335072/test.zip)
2. Open a terminal in the extracted folder
3. Run the following commands (tested on Windows):
  ``` sh
dotnet restore
dotnet build
dotnet tool restore
dotnet tool run swagger tofile ./bin/Debug/net8.0/test.dll v1
  ```
4. See it chrash due to line 8 in Program.cs `throw new InvalidOperationException("My error message");`
    Notice it doesn't say `My error message`, but `A type named 'StartupProduction' or 'Startup' could not be found in assembly 'test'`

### Exception(s) (if any)

```
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'Backend'.
         at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
         at Microsoft.AspNetCore.Hosting.WebHostBuilder.ScanAssemblyAndRegisterStartup(ServiceCollection services, String startupAssemblyName)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass15_1.<ScanAssemblyAndRegisterStartup>b__1(IServiceProvider _)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
         at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
         at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
         at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
         at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
         at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 145
         at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
         at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
         at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
         at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
```

### Swashbuckle.AspNetCore version

6.6.1

### .NET Version

NET8.0

**Comment by martincostello** [comment]
That exception message is coming from ASP.NET Core, not us.
