### ISSUE TITLE
[Bug]: Exception thrown: 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException' in System.Private.CoreLib.dll with version 6.6.x

### ISSUE THREAD

**Issue by fhurta** [domaindrivendev/Swashbuckle.AspNetCore#2989]
### Describe the bug

Please improve problem reporting.

After upgrading from 6.4.0 to 6.6.2, the swagger.json file was not generated. Downgrading to 6.5.0 fixed the issue. Nor 6.6.1 neither 6.6.2 version worked, however.
The project (ASPNET Core API) was recently upgraded to net8 from net6 (historically it undergone upgrades from 2.2 -> 3.1 -> 6 -> 8)

The SwaggerUI page loads but it shows error:
Failed to load API definition.
Fetch error
response status is 500 /swagger/v1/swagger.json

Browser (Chrome current) shows following error for request https://localhost:44355/swagger/v1/swagger.json
500 Internal Server Error
Something got wrong. Error correlationId: de3b5347-48fd-4bcb-ac52-50675a5e6a96

VS Output shows:
Exception thrown: 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException' in System.Private.CoreLib.dll

Before sending this bug report I found out the root cause of the problem. There was used IFormFile with attribute [FromForm]. I was quite lucky to find the problem by removing controllers from the project (there are approx 70 controllers), But the error message really didn't help.

### Expected behavior

The swagger file is generated or reasonable error/exception is emitted

### Actual behavior

The swagger file fails to generate and Swagger UI shows error 500

### Steps to reproduce

add method with signature to a controller:

public async Task<ActionResult<string>> UploadFile([FromRoute] int assessmentId, [FromForm(Name = "file")] IFormFile file)

### Exception(s) (if any)

Exception thrown: 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException' in System.Private.CoreLib.dll

### Swashbuckle.AspNetCore version

6.6.x

### .NET Version

8.0.303

**Comment by martincostello** [comment]
Can you provide a stack trace or a minimal repro of the issue?

**Comment by fhurta** [comment]
There was no stack trace, that's the point. No clue, just a single line in VS output window:
'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException' in System.Private.CoreLib.dll

The repro steps are described - just add a method with the signature described into a controller and it should be reproduced.
Using up to date Visual Studio, net8. 

Printing out the full exception with the stack trace is actually all I would like to have for troubleshooting :)

**Comment by martincostello** [comment]
That just seems really weird. What if you configure Visual Studio to break whenever that type of exception is thrown?

I would expect that Visual Studio would normally either break at that point if it's genuinely unhandled, or the developer exception page to show you something.

Plus we have tests for form handling, which is why I asked if there's a more specific repro. If not we can look into it, it just seems odd that there's no way for you to see the exception at all with all with Visual Studio, as it can clearly see enough to tell you there's an exception happening at all.

Stack traces in issues also mean I can guess at what's wrong just from issues on my phone when I'm not at a computer 🙂

**Comment by martincostello** [comment]
I added the following to our existing [`FromFormParamsController`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/3553751127f9b514f49f708eba4705b623745f1a/test/WebSites/Basic/Controllers/FromFormParamsController.cs#L7) class used in our tests:

```csharp
[HttpPost("github-issue-2989/{assessmentId}")]
public async Task<ActionResult> GitHubIssue2989([FromRoute] int assessmentId, [FromForm(Name = "file")]  IFormFile file)
{
    await Task.CompletedTask;
    throw new System.NotImplementedException();
}
```

Running the tests, I get this failure:

```text
    Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Basic.Controllers.FromFormParamsController.GitHubIssue2989 (Basic). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Error reading parameter(s) for action Basic.Controllers.FromFormParamsController.GitHubIssue2989 (Basic) as [FromForm] attribute used with IFormFile. Please refer to https://github.com/domaindrivendev/Swashbuckle.AspNetCore#handle-forms-and-file-uploads for more information
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParametersAsync(ApiDescription apiDescription, SchemaRepository schemaRespository, Func`3 parameterGenerator) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 512
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParametersAsync(ApiDescription apiDescription, SchemaRepository schemaRespository) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 550
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 322
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository, Func`3 parametersGenerator, Func`3 bodyGenerator, Func`3 applyFilters) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 345
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationAsync(ApiDescription apiDescription, SchemaRepository schemaRepository) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 373
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperationsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 268
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository, Func`3 operationsGenerator) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 207
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePathsAsync(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 229
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.SwaggerGen\SwaggerGenerator\SwaggerGenerator.cs:line 56
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) in C:\Coding\domaindrivendev\Swashbuckle.AspNetCore\src\Swashbuckle.AspNetCore.Swagger\SwaggerMiddleware.cs:line 64
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

I get the same error from 13 failing tests if I add `[FromForm(Name = "file")]` to [this controller method](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/3553751127f9b514f49f708eba4705b623745f1a/test/WebSites/Basic/Controllers/FilesController.cs#L12).

If I remove `[FromForm(Name = "file")]` as [the link](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#handle-forms-and-file-uploads) states, then I get this:

```text
Assert.Empty() Failure: Collection was not empty
Collection: [Declared path parameter "assessmentId" needs to be defined as a path parameter at either the path or operation level [#/paths/~1github-issue-2989/post/parameters/0/in]]
```

This failure is part of an end-to-end test and the exception is from the HTTP response content, so I can only assume that you have configured your site and/or Visual Studio in some way that obscured the exception from your view. If you fix whatever the reason for that is, you should see the exception in your logs somewhere pointing you to the documentation on how to fix your endpoint.
