### ISSUE TITLE
[Bug]: File upload using [FromForm] IFormFile file throws an error

### ISSUE THREAD

**Issue by Qiulin-Git** [domaindrivendev/Swashbuckle.AspNetCore#2996]
### Describe the bug

File upload using [FromForm] IFormFile file throws an error：
An unhandled exception has occurred while executing the request.

Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - QiuLin.Web.Core.Areas.Admin.Controllers.FileController.UploadFileAsync (QiuLin.Web.Core). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Error reading parameter(s) for action QiuLin.Web.Core.Areas.Admin.Controllers.FileController.UploadFileAsync (QiuLin.Web.Core) as [FromForm] attribute used with IFormFile. Please refer to https://github.com/domaindrivendev/Swashbuckle.AspNetCore#handle-forms-and-file-uploads for more information
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameters(ApiDescription apiDescription, SchemaRepository schemaRespository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   --- End of inner exception stack trace ---
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### Steps to reproduce

 [HttpPost]
 public async Task<IActionResult> UploadFileAsync([FromForm] IFormFile file)
{
}

### Swashbuckle.AspNetCore version

6.62

### .NET Version

net8.0

**Comment by martincostello** [comment]
> [FromForm] attribute used with IFormFile. Please refer to https://github.com/domaindrivendev/Swashbuckle.AspNetCore#handle-forms-and-file-uploads for more information

See exception message.

**Comment by panichajai** [comment]
use >  https://stackoverflow.com/questions/70668520/how-to-get-a-upload-button-in-swagger-for-iformfile-combined-with-other-properti
