### ISSUE TITLE
500 Errors while trying to load swagger.json file

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [domaindrivendev/Swashbuckle.AspNetCore#302]
I installed the nuget package as described, configured my startup.cs file as described.
I can get to the /swagger/index.html file, but it shows a 500 error getting the .json file
If i try the path to the .json file directly I get a 500

I loaded up my trace logs and found:

<img width="1440" alt="screen shot 2017-02-16 at 10 19 32 am" src="https://cloud.githubusercontent.com/assets/1190629/23030451/65a286f2-f433-11e6-9378-c50ea7f4c1a5.png">

Am I missing something?

**Comment by Redgwell** [comment]
I had the same issue - if you run your app using `dotnet run` from the command line, you'll get more details about the error. 

For me, it was this:

```
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "FEFDSIH342": An unhandled exception was thrown by the application.
System.NotSupportedException: Ambiguous location (path, query etc.) for one or more parameters in action - ExampleController.TestAction (TestNamespace). Action parameters require an explicit "From" binding for Swagger
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetParameterLocation(ApiDescription apiDescription, ApiParameterDescription paramDescription)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateParameter(ApiDescription apiDescription, ApiParameterDescription paramDescription, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

My issue was that I had an action that had parameters without any attribute - My specific usecase was to add the `[FromRoute] ` decoration.

**Comment by SmarterPhoneLabs** [comment]
Yeah, I just discovered the same exact thing.
I guess they are trying to enforce TRUE REST ;)

Thanks for the reply!

**Comment by jotatoledo** [comment]
For ppl migrating .NET Web API projects to .NET Core:

Had a similar issue, deleting the `.vs` folder solved it
