### ISSUE TITLE
[Bug]: System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly

### ISSUE THREAD

**Issue by MitchellW-DWL** [domaindrivendev/Swashbuckle.AspNetCore#3082]
### Describe the bug

Have been following https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2168 and have tried all the described solutions there, running locally this works fine, running in PR checks it works fine, but then when running a deploy this breaks.

I'm on .net8 using swashbuckle 6.5.0 _(Have tried with original version 6.2.3 and newest 6.8.0 too)_ it seemed to happen somewhat intermittently in the past but retrying the workflow would eventually get it through however now it's failing continuously.

<details><summary>`dotnet-tools.json`</summary>
<p>

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "swashbuckle.aspnetcore.cli": {
      "version": "6.5.0",
      "commands": [
        "swagger"
      ]
    }
  }
}
```

</p>
</details>

<details><summary>csproj</summary>
<p>

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DWL.Lib.Auth" Version="8.0.0-beta-10902437656" />
        <PackageReference Include="Mapster" Version="7.3.0" />
        <PackageReference Include="Mapster.DependencyInjection" Version="1.0.0" />
        <PackageReference Include="Serilog" Version="3.0.0-dev-02028" />
        <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Speechy.Service\Speechy.Service.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include=".config\dotnet-tools.json" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="dotnet tool restore" />
        <Exec Command="dotnet swagger tofile --output api.json $(OutputPath)\$(AssemblyName).dll v1" />
    </Target>
    
</Project>
```

</p>
</details>

<details><summary>Action build step</summary>
<p>

```yml
    - name: 🔨 Build
      run: dotnet build --no-restore -c Release
      env:
        API_IMPORT_DLL: 'Speechy/Speechy/Speechy.WebApi/bin/Release/net8.0/Speechy.WebApi.dll'
        SWASHBUCKLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.5.0
        API_IMPORT_VERSION: v1
        CONFIGURATION: Release
```

</p>
</details> 

Only difference between the PR check that works building the project and generating swagger json that I can discern is one is production, other is not but building in production locally works fine.

### Expected behavior

Get a swagger openapi json spec

### Actual behavior

Exception thrown

### Exception(s) (if any)

```
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'Speechy.WebApi'.
     at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
     at Microsoft.AspNetCore.Hosting.WebHostBuilder.ScanAssemblyAndRegisterStartup(ServiceCollection services, String startupAssemblyName)
  --- End of stack trace from previous location ---
     at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass15_1.<ScanAssemblyAndRegisterStartup>b__1(IServiceProvider _)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
     at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
     at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
     at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
     at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
     at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
     at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
     at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
     at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
     at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
     at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 145
     at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 82
     at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 68
     at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\CommandRunner.cs:line 59
     at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in C:\projects\ahoy\src\Swashbuckle.AspNetCore.Cli\Program.cs:line 121
/home/runner/work/Speechy/Speechy/Speechy.WebApi/Speechy.WebApi.csproj(59,9): error MSB[30](https://github.com/dwlgit/Speechy/actions/runs/11048775286/job/30692886141#step:6:31)73: The command "dotnet swagger tofile --output api.json bin/Release/net8.0//Speechy.WebApi.dll v1" exited with code 134.
```

### Swashbuckle.AspNetCore version

6.2.3, 6.4.0, 6.5.0, 6.8.0

### .NET Version

.net8.0

### Anything else?

Have been looking at all the following
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2168
Tried having a blank `appsettings.Production.json` file but still threw same error along with the different suggested versions

Have followed
https://stackoverflow.com/questions/78406014/system-invalidoperationexception-a-type-named-startupproduction-or-startup
Trying the suggest env vars for the step, but inclusion of them didnt seem to work and confirmed the file path is correct _(Worth noting I only tried adding these after it started failing as didnt need them before that point)_

Please let me know if there's anything else I can provide

**Comment by MitchellW-DWL** [comment]
@martincostello Here's your new issue 👍

**Comment by martincostello** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) as a GitHub repository that demonstrates the issue you're experiencing so we can look into this further.

Support for Minimal APIs has been working in general for others, so I feel that this issue is something specific to how your project is set up (given how the exception isn't coming from our code).

We need something we can actually debug to look into to get towards any kind of resolution.

As a starting point, using the latest version will be a step forward you'll need as versions since 6.7.0 target `net8.0` and also contain other bug fixes related to the CLI.

**Comment by MitchellW-DWL** [comment]
> Support for Minimal APIs has been working in general for others, so I feel that this issue is something specific to how your project is set up (given how the exception isn't coming from our code).

Yeah this project doesn't use the minimal hosting - I'll try to find some time to replicate the issue but given it's intermittent it might be a struggle as the last instance I setup worked with no differences I could discern

**Comment by DenKn** [comment]
I have no Minimal API in my project.
But I've got the same issue 

**Swashbuckle.AspNetCore version** - 6.8.1

**.NET Version** - .net8.0

**Comment by rodrigopinto** [comment]
Same here:

**.Net version:** 8.0.404
Swashbuckle.AspNetCore version: 7.0.0 or 6.9.0

The weird is that it was working fine with the 6.9.0. As soon I upgraded to 7.0.0 it stop to work. Now, even when I downgrade the version, the error persists.

**Comment by martincostello** [comment]
Likely reason is related to dependencies in the build output causing resolution issues. Try cleaning your build output.

**Comment by rodrigopinto** [comment]
Quick reviewing the code on Github, the error is here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Cli/Program.cs#L183-L186 for the version 7.0.0 following my stack trace


```sh
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.ScanAssemblyAndRegisterStartup(ServiceCollection services, String startupAssemblyName)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass15_1.<ScanAssemblyAndRegisterStartup>b__1(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Swashbuckle.AspNetCore.Cli.Program.GetServiceProvider(Assembly startupAssembly) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 183
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_4(IDictionary`2 namedArgs) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 88
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 68
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable`1 args) in /_/src/Swashbuckle.AspNetCore.Cli/CommandRunner.cs:line 59
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args) in /_/src/Swashbuckle.AspNetCore.Cli/Program.cs:line 159
3````

Navigating a bit on the error, it seems it the block of error as the cli does inflection and cant find the right method to access the assembly.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/beaf75cc64cc79f6e8c08f9a3ac977f0e1e705c9#diff-d76594f077d2b9007e19e6ca6d48332393da4eda1d8571560b78ec6c72da7a2bR83

**Comment by rodrigopinto** [comment]
I have not parked time to investigate this, but this issue should still exist.

**Comment by Farllon** [comment]
Adding this code to `Program.cs` solve my problem:
``` csharp
var builder = WebApplication.CreateBuilder(args);
...

// This code solved my problem
namespace MyApp {
    public class Startup;
}
```

**Comment by jknust** [comment]
> Adding this code to `Program.cs` solve my problem:
> 
> var builder = WebApplication.CreateBuilder(args);
> ...
> 
> // This code solved my problem
> namespace MyApp {
>     public class Startup;
> }

Was this in a dotnet 9 app? I tried the same and was still encountering the issue.

**Comment by Farllon** [comment]
> > Adding this code to `Program.cs` solve my problem:
> > var builder = WebApplication.CreateBuilder(args);
> > ...
> > // This code solved my problem
> > namespace MyApp {
> > public class Startup;
> > }
> 
> Was this in a dotnet 9 app? I tried the same and was still encountering the issue.

No, in my case my applications are in .NET 8.

In my scenario, this error does not occur locally when I run the Swashbuckle.AspNetCore.Cli tool, but it does occur within the deployment pipeline of our services.

An interesting point is that it does not occur in all services, even if they use the same version of the library and also use .NET 8.

**Comment by negberts** [comment]
It happens for us when package Azure.Monitor.OpenTelemetry.AspNetCore is added to the API. 

Without it no errors, with the same errors as above. 

.NET 8

**Comment by dstenroejl** [comment]
We experienced the same error in .NET 9.

The solution to us was inspired by this comment: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2355#issuecomment-1845698851

Whenever we use tools to generate output (swagger or graphql schema), we now set an environment variable like explained in the comment. During startup we then skip the registration/configuration of "OpenTelemetry" and "Azure App Configuration" if this environment variable is set.

**Comment by kant2002** [comment]
I experience this issue in f# project, I manage narrow down to 1 route which produce error.
```fsharp
type DoRouteRequest =
    {
        [<FromForm>]
        p1: string
        [<FromForm>]
        p2: IFormFile
        [<FromForm>]
        p3: IFormFile | null
        [<FromForm>]
        p4: IFormFile

        httpContextAccessor: IHttpContextAccessor
        userManager: UserManager<ApplicationUser>
        logger: ILogger<DoRouteRequest>
    }

post "/route" doRoute (fun c -> c.RequireAuthorization().DisableAntiforgery())
```

I will try to narrow down further. Let's see if I can do something

**Comment by holly-hacker** [comment]
We're encountering this at work which seems to be because we're hitting the 30s timeout introduced in #2381. Could be a useful point to investigate for others that find this issue through google.
