### ISSUE TITLE
Add better null checking to XML comment filter.

### ISSUE THREAD

**Issue by KallDrexx** [domaindrivendev/Swashbuckle.AspNetCore#348]
In RC3 of this library from Nuget, I am trying to utilize our C# xml comments to give swagger descriptions where possible.  Unfortunately, when I I add `setup.IncludeXmlComments(xmlPath)` I get a `NullReferenceException` with the following stack trace.

```
at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.<>c.<ApplyPropertiesXmlToPropertyParameters>b__11_0(ApiParameterDescription p)\r\n   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.ApplyPropertiesXmlToPropertyParameters(IList`1 parameters, ApiDescription apiDescription)
at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.Apply(Operation operation, OperationFilterContext context)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at Project.Api.Application.Middleware.RequestTracingMiddleware.<Invoke>d__3.MoveNext() in e:\\Code\\Work\\<Project>\\Application\\Middleware\\RequestTracingMiddleware.cs:line 37"
```

Unfortunately, this makes it impossible for me to figure out what's wrong without downloading this source code and debugging with a direct project reference.

**Comment by ruant** [comment]
#316

**Comment by KallDrexx** [comment]
Sorry, I tried to search and apparently failed :(
