### ISSUE TITLE
SetCookieHeaderValue .net core 2

### ISSUE THREAD

**Issue by cinohee** [domaindrivendev/Swashbuckle.AspNetCore#502]
`
Find all "System.MissingMethodException: Method not found: 'Void Microsoft.Net.Http.Headers.SetCookieHeaderValue..ctor(System.String)'.
   at Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager.AppendResponseCookie(HttpContext context, String key, String value, CookieOptions options)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleSignInAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.SignInManager`1.<SignInAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.SignInManager`1.<SignInOrTwoFactorAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.SignInManager`1.<PasswordSignInAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Identity.SignInManager`1.<PasswordSignInAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServerAPI.Controllers.Account.LoginController.<Post>d__6.MoveNext() in C:\Projects\NedaWorkSpace\Nic\Server API\ServerAPI\ServerAPI\Controllers\Account\LoginController.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous ", Find Results 1, Entire Solution, ""
  Matching lines: 0    Matching files: 0    Total files searched: 461

{
  "name": "Microsoft.ApplicationInsights.Dev.Exception",
  "time": "2017-10-04T01:33:19.5710976Z",
  "tags": {
    "ai.operation.parentId": "|e0c6bcbb-45bc0cdd738790b1.",
    "ai.operation.name": "POST Login/Post",
    "ai.operation.id": "e0c6bcbb-45bc0cdd738790b1",
    "ai.cloud.roleInstance": "WIN-S7NR41160FE",
    "ai.location.ip": "127.0.0.1",
    "ai.application.ver": "1.0.0.0",
    "ai.internal.sdkVersion": "aspnet5c:2.1.1",
    "ai.internal.nodeName": "WIN-S7NR41160FE"
  },
  "data": {
    "baseType": "ExceptionData",
    "baseData": {
      "ver": 2,
      "properties": {
        "DeveloperMode": "true",
        "handledAt": "Platform",
        "AspNetCoreEnvironment": "Development"
      },
      "exceptions": [
        {
          "id": 60275781,
          "typeName": "System.MissingMethodException",
          "message": "Method not found: 'Void Microsoft.Net.Http.Headers.SetCookieHeaderValue..ctor(System.String)'.",
          "hasFullStack": true,
          "parsedStack": [
            {
              "level": 0,
              "method": "Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager.AppendResponseCookie",
              "assembly": "Microsoft.AspNetCore.Authentication.Cookies, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 1,
              "method": "Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler+<HandleSignInAsync>d__15.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication.Cookies, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 2,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 3,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 4,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationHandler`1+<SignInAsync>d__66.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 5,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 6,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 7,
              "method": "Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager+<SignInAsync>d__14.MoveNext",
              "assembly": "Microsoft.AspNetCore.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 8,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 9,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 10,
              "method": "Microsoft.AspNetCore.Identity.SignInManager`1+<SignInAsync>d__29.MoveNext",
              "assembly": "Microsoft.AspNetCore.Identity, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 11,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 12,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 13,
              "method": "Microsoft.AspNetCore.Identity.SignInManager`1+<SignInOrTwoFactorAsync>d__48.MoveNext",
              "assembly": "Microsoft.AspNetCore.Identity, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 14,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 15,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 16,
              "method": "Microsoft.AspNetCore.Identity.SignInManager`1+<PasswordSignInAsync>d__32.MoveNext",
              "assembly": "Microsoft.AspNetCore.Identity, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 17,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 18,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 19,
              "method": "Microsoft.AspNetCore.Identity.SignInManager`1+<PasswordSignInAsync>d__33.MoveNext",
              "assembly": "Microsoft.AspNetCore.Identity, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 20,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 21,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 22,
              "method": "System.Runtime.CompilerServices.TaskAwaiter`1.GetResult",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 23,
              "method": "ServerAPI.Controllers.Account.LoginController+<Post>d__6.MoveNext",
              "assembly": "ServerAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
              "fileName": "D:\\Projects\\Nic\\Server API\\ServerAPI\\ServerAPI\\Controllers\\Account\\LoginController.cs",
              "line": 55
            },
            {
              "level": 24,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 25,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 26,
              "method": "lambda_method",
              "assembly": "Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
            },
            {
              "level": 27,
              "method": "Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 28,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 29,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 30,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 31,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 32,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 33,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 34,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 35,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 36,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 37,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 38,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 39,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 40,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 41,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 42,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 43,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 44,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 45,
              "method": "Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext",
              "assembly": "Microsoft.AspNetCore.Mvc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 46,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 47,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 48,
              "method": "Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext",
              "assembly": "Microsoft.AspNetCore.Routing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 49,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 50,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 51,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 52,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 53,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 54,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 55,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 56,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 57,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 58,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 59,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 60,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 61,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 62,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 63,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 64,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 65,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 66,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 67,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 68,
              "method": "Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1+<Invoke>d__18.MoveNext",
              "assembly": "Microsoft.AspNetCore.Authentication, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 69,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 70,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 71,
              "method": "Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__7.MoveNext",
              "assembly": "Microsoft.AspNetCore.Cors, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 72,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 73,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 74,
              "method": "Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware+<Invoke>d__11.MoveNext",
              "assembly": "Microsoft.AspNetCore.Server.IISIntegration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 75,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 76,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 77,
              "method": "Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware+<Invoke>d__3.MoveNext",
              "assembly": "Microsoft.AspNetCore.Hosting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            },
            {
              "level": 78,
              "method": "System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 79,
              "method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
              "assembly": "System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
            },
            {
              "level": 80,
              "method": "Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1+<ProcessRequestsAsync>d__2.MoveNext",
              "assembly": "Microsoft.AspNetCore.Server.Kestrel.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
            }
          ]
        }
      ]
    }
  }
}`

**Comment by oofpez** [comment]
I get this too

**Comment by domaindrivendev** [comment]
You might want to read through the comments #438. There may be dependencies brought in by SB that aren't compatible with the version of ASP.NET Core you're running. The workaround is to explicitly reference those dependencies yourself so that a compatible version is brought in as opposed to the minimum version that SB depends on.

**Comment by domaindrivendev** [comment]
Closing due to inactivity
