### ISSUE TITLE
Response Compression crashes application

### ISSUE THREAD

**Issue by ChaosEngine** [domaindrivendev/Swashbuckle.AspNetCore#600]
For version 1.2.0 when HTTP output compression is enabled

```
services.AddResponseCompression();
...
app.UseResponseCompression();
```

I got following error and app crash when opening swagger page:

```
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/swagger/ui/
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLBO77K0F300", Request id "0HLBO77K0F300:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 200.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.HandleNonBodyResponseWrite()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.<WriteAsyncAwaited>d__199.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.PurgeBuffers(Boolean disposing)
   at System.IO.Compression.DeflateStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Compression.GZipStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Microsoft.AspNetCore.ResponseCompression.BodyWrapperStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 472.1746ms 200 text/html

Unhandled Exception: System.ObjectDisposedException: Can not access a closed Stream.
   at System.IO.Compression.DeflateStream.EnsureNotDisposed()
   at System.IO.Compression.DeflateStream.CheckEndXxxxLegalStateAndParams(IAsyncResult asyncResult)
   at System.IO.Compression.DeflateStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Compression.GZipStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.ResponseCompression.BodyWrapperStream.<WriteAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<RespondWithIndexHtml>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Objectstate, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

using version:

```
<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="1.2.0" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="1.2.0" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="1.2.0" />
```
and

`<TargetFramework>net461</TargetFramework>`

Problem does not exist on 1.0.0 version

**Comment by ChaosEngine** [comment]
Can be reproduced with internal test WebSites project by enabling 
`
<TargetFramework>net461</TargetFramework>
`

and adding 

```
services.AddResponseCompression();
...
app.UseResponseCompression();

```

**Comment by domaindrivendev** [comment]
This doesn't repro for me with SB 2.1.0

**Comment by ChaosEngine** [comment]
Try to apply my diff on root of project. test\WebSites\Basic is being changed, and on first run (with net461) it crashes the dotnet process.
Surprisingly I've pinpointed the root cause of the problem is located here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIIndexMiddleware.cs#L52
If changed to
```
//await response.WriteAsync(htmlBuilder.ToString(), Encoding.UTF8);
var buff = Encoding.UTF8.GetBytes(htmlBuilder.ToString());
response.Body.Write(buff,0,buff.Length);
```
it works properly. Clearly it is not linked with Swashbuckle.AspNetCore recent changes, but to https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.ResponseCompression
to which I will be reporting this issue.

**Comment by albator1932** [comment]
Yep, have the same thing on my side since 1.2.0 all the way up to 2.1.0. I definitely cannot afford removing response compression in my API though so I guess I'm stuck with 1.1.0 for now until this is fixed in BasicMiddleware

**Comment by domaindrivendev** [comment]
@ChaosEngine - thanks for investigating this. Can you see any potential downside to the workaround. I'd be happy to implement it, just not sure if there's potential for unintended side affects

**Comment by ChaosEngine** [comment]
Will try to test it more thoroughly. In worst case some _#ifdef NET461_ might be useful.

**Comment by albator1932** [comment]
In my case, the API is targeted for .NET 4.6.2 so it looks like it's not strictly related to 4.6.1

**Comment by ChaosEngine** [comment]
@albator1932 it does not really matter, core vs full net framework is the difference

**Comment by caglarsarikaya** [comment]
> Try to apply my diff on root of project. test\WebSites\Basic is being changed, and on first run (with net461) it crashes the dotnet process. Surprisingly I've pinpointed the root cause of the problem is located here https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIIndexMiddleware.cs#L52 If changed to
> 
> ```
> //await response.WriteAsync(htmlBuilder.ToString(), Encoding.UTF8);
> var buff = Encoding.UTF8.GetBytes(htmlBuilder.ToString());
> response.Body.Write(buff,0,buff.Length);
> ```
> 
> it works properly. Clearly it is not linked with Swashbuckle.AspNetCore recent changes, but to https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.ResponseCompression to which I will be reporting this issue.

Thank you. It was really nice
