### ISSUE TITLE
dotnet-swagger Path Directory seperator

### ISSUE THREAD

**Issue by drjaydenm** [domaindrivendev/Swashbuckle.AspNetCore#602]
Hi there, we are using dotnet-swagger to generate the JSON document from the command-line. It works perfect on Windows, however on Linux, it has what looks to be a directory separator issue.
We are using version 1.2.0 (1.2.0-beta1 of the dotnet-swagger tool)

Running the tool using the following command can repro the issue on linux.
`dotnet swagger tofile "bin/Debug/netcoreapp2.0/OurApi.dll" v1 "bin/Debug/netcoreapp2.0/OurApi.json"`

Results in

`Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/mnt/f/Projects/ourapi/OurApi\bin/Debug/netcoreapp2.0/OurApi.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at Swashbuckle.AspNetCore.Cli.Program.<>c.<Main>b__0_3(IDictionary2 namedArgs)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable1 args)
   at Swashbuckle.AspNetCore.Cli.CommandRunner.Run(IEnumerable1 args)
   at Swashbuckle.AspNetCore.Cli.Program.Main(String[] args)`

You can see that a Windows-style directory separator has been inserted into the path
`/mnt/f/Projects/ourapi/OurApi\bin/Debug/netcoreapp2.0/OurApi.json`

We even tried using the following command to no avail
`dotnet swagger tofile "/mnt/f/Projects/ourapi/OurApi/bin/Debug/netcoreapp2.0/OurApi.dll" v1 "/mnt/f/Projects/ourapi/OurApi/bin/Debug/netcoreapp2.0/OurApi.json"`

Results in the following path in the error message
`/mnt/f/Projects/ourapi/OurApi\/mnt/f/Projects/ourapi/OurApi/bin/Debug/netcoreapp2.0/OurApi.dll`

Thanks

**Comment by drjaydenm** [comment]
From a quick look at the source code, it looks like the error is coming from [this line](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/67673c27dcc1bb2094d8d0b990900befc8abd602/src/Swashbuckle.AspNetCore.Cli/Program.cs#L80)

**Comment by domaindrivendev** [comment]
This should solve it - 069aa9442cc258cae48eb5be9026a23dab528c27.

Will be part of major 2.0.0 release coming real soon. In the meantime though, you can pull the preview down from myget:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore.Cli

Please note a small change to the usage from 1.2.0: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#swashbuckleaspnetcorecli

**Comment by drjaydenm** [comment]
Thanks, that looks like it should fix the problem, I'll await the new release to try it out.

**Comment by domaindrivendev** [comment]
@drjaydenm - let me know if this works so I can close the issue.

**Comment by domaindrivendev** [comment]
Works for me, so closing issue for now

**Comment by drjaydenm** [comment]
Thanks @domaindrivendev, it's generating the JSON correctly now on Linux.
