### ISSUE TITLE
SwaggerGenOptions.CreateSwaggerProvider throws FileNotFound Microsoft.Extensions.Options.xml

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [domaindrivendev/Swashbuckle.AspNetCore#709]
In an aspnetcore project targeting dotnetcore, when enabling doc comments for use when generating swagger like this:

            var basePath = Assembly.GetCallingAssembly().Location;
            var xmlPath = Path.ChangeExtension(basePath, "xml");
            options.IncludeXmlComments(xmlPath);

I see this exception:

System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.extensions.options\2.0.1\lib\netstandard2.0\Microsoft.Extensions.Options.xml'.
File name: 'C:\Program Files\dotnet\store\x64\netcoreapp2.0\microsoft.extensions.options\2.0.1\lib\netstandard2.0\Microsoft.Extensions.Options.xml'
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass28_0.<IncludeXmlComments>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

It's quite sensitive depending on small changes -- sometimes it goes away and then I make a change and it comes back.

The problem is that the file 'Microsoft.Extensions.Options.xml' doesn't exist and it doesn't matter whether I explicitly include the nuget package Microsoft.Extensions.Options or not. I can't find any mention of the file other outside the Microsoft.Extensions.Options package and certainly my doc comments don't mention it at all.

Any ideas?

Thanks!

Henrik

**Comment by HenrikFrystykNielsen** [comment]
I think I figured it out -- the calling assembly is was causes it. Never mind :)

**Comment by dale-french** [comment]
@HenrikFrystykNielsen i'm having the same issue - how did you resolve it?

Usings:
```
using Swashbuckle.AspNetCore.Swagger;
using System.IO;
using System.Reflection;
```

Code:
```
var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
c.IncludeXmlComments(xmlPath);
```

Thanks!

**Comment by HenrikFrystykNielsen** [comment]
My issue was with the assembly being shadow copied. In this case, it ends up in some random folder without the associated XML file. Assembly.Location points to that location and so it can't find the XML file leading to the error above. The trick was to see that if you are shadow copied then use Assembly.CodeBase which in most cases should give you the location where the XML file is located.
