### ISSUE TITLE
Swashbuckle.AspNetCore.SwaggerGen.TypeExtensions.FullNameSansTypeArguments(Type type) in TypeExtensions.cs, line 20

### ISSUE THREAD

**Issue by cnlizhipeng** [domaindrivendev/Swashbuckle.AspNetCore#715]
My abstract class has this function

`void Delete(ICollection<KeyType> input);`

There will be a mistake

I tried to modify the following code to solve my problem.
```
 internal static string FullNameSansTypeArguments(this Type type)
        {
                var fullName = type.FullName??type.ToString();
                var chopIndex = fullName.IndexOf("[[");
                return (chopIndex == -1) ? fullName : fullName.Substring(0, chopIndex);
        }
```
Are there any other better things to do, or my use is wrong?

**Comment by aspnetlabs** [comment]
Hi, I am facing a similar issue.

My application source code 
https://github.com/aspnetlabs/Dynamic-WebAPI-Controllers

This is the stack trace:

> 

 Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HLE3ADDEN75D": An unhandled exception was thrown by the application.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.SwaggerGen.TypeExtensions.FullNameSansTypeArguments(Type type)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsMemberNameHelper.BuildTypeToken(Type type)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsMemberNameHelper.GetMemberNameForMethod(MethodInfo method)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.Apply(Operation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at 

> Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by PatrickTetz** [comment]
Just faced the same issue on a generic class, any news?

**Comment by domaindrivendev** [comment]
Also, see the link below - I've come up with a test to repro but have it commented out because I haven't had the time to find a solution. Those XML comments member names are extremely cryptic, particularly when generics come into play and I haven't had the time to give it the focus it needs:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/XmlCommentsMemberNameHelperTests.cs#L29

**Comment by domaindrivendev** [comment]
If anyone else wants to pull it down and take a stab that would be awesome?

**Comment by domaindrivendev** [comment]
@cnlizhipeng, @aspnetlabs, @PatrickTetz I believe I've implemented a fix for this, pushed with the following commit - 0b6e0b2

It should be available with the following preview package on myget.org:

`Swashbuckle.AspNetCore.2.5.0-preview-0510.nupkg`

Could you please pull it down, test it out and provide feedback? Thanks
