### ISSUE TITLE
IncludeXmlComments generate exception when I use one EF Command(Add-Migration/Update-Migration/Remove-Migration)

### ISSUE THREAD

**Issue by regis-ranniere** [domaindrivendev/Swashbuckle.AspNetCore#748]
Hello,

I'm getting a Issue very strange in my application.
When I run some entity framework core command to generate a migration I'm get a exception on : 
`Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass28_0.<IncludeXmlComments>b__0()`

 In my startup have a configuration of SwaggerGen: 
```
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1",
                    new Info
                    {
                        Title = "Test - API",
                        Description = "Test Desc ",
                        Version = "v1"
                    });
               var xmlFile = $"{Assembly.GetEntryAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                options.IncludeXmlComments(xmlPath);
            });
```
If I comment line  `options.IncludeXmlComments(xmlPath);` everything works fine.
Instead I get this exception:

```
PM> Remove-Migration -c IdentityContexto
Application startup exception: System.IO.FileNotFoundException: Could not find file 'C:\VSTS\Project\One\src\Project.One.Api\bin\Debug\netcoreapp2.1\ef.xml'.
File name: 'C:\VSTS\Project\One\src\Project.One.Api\bin\Debug\netcoreapp2.1\ef.xml'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.<>c__DisplayClass28_0.<IncludeXmlComments>b__0()
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
```
I'm realy confused, because this exeception is about ef, but this happen with IncludeXmlComments.
In runtime my application works fine too...

Any suggestions? Is realy about SwaggerDoc or ef?

**Comment by regis-ranniere** [comment]
I update EFCore to version 2.1 and everythings works fine.
