### ISSUE TITLE
Runtime in generic paramter

### ISSUE THREAD

**Issue by ErliSoares** [domaindrivendev/Swashbuckle.AspNetCore#751]
ASP.NET Core Version: 2.0
Swashbuckle.AspNetCore Version: 2.4.0

- [X] Bug Reports
- [ ] Feature Requests
- [ ] Pull Requests

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Swashbuckle.AspNetCore.SwaggerGen.TypeExtensions.FullNameSansTypeArguments(Type type)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsMemberNameHelper.BuildTypeToken(Type type)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsMemberNameHelper.GetMemberNameForMethod(MethodInfo method)
   at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsOperationFilter.Apply(Operation operation, OperationFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, ISchemaRegistry schemaRegistry)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Source code to reproduce the error:
```CSHARP
public abstract class TestAbstractController<T> : Controller
{
    /// <summary>
    /// Documentation test
    /// </summary>
    /// <param name="key">Test paramter</param>
    [HttpPatch("{key:int:min(0)}")]
    public void TestData(int key, [FromBody] TestDataGeneric<T> value)
    {
    }
}

[Produces("application/json")]
[Route("api/[controller]")]
public class TestController : TestAbstractController<int>
{
        
}
    
public class TestDataGeneric<T>
{
        
}
```

**Comment by domaindrivendev** [comment]
I believe this is a dup of #715

Also, see the link below - I've come up with a test to repro but have it commented out because I haven't had the time to find a solution. Those XML comments member names are extremely cryptic, particularly when generics come into play and I haven't had the time to give it the focus it needs:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Annotations/XmlCommentsMemberNameHelperTests.cs#L29
