### ISSUE TITLE
operationId and summary fields not set to expected values

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [domaindrivendev/Swashbuckle.AspNetCore#921]
Versions:
```    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="3.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Examples" Version="2.9.0" />
```

Here is my endpoint defintiion:

```
        /// <summary>
        /// An example endpoint that can be accessed with a GET to v1/example/values
        /// Be default, endpoints allow anonymous callers.
        /// </summary>
        [HttpGet]
        [Route("values"), Produces("application/json")]
        [SwaggerOperation("ReadExample")]
        public Task<Example> ReadExample(CancellationToken cancellationToken)
        {
            return _exampleService.GetAllAsync(cancellationToken);
        }
```

This generates swagger:

```
    "/v1/example/values": {
      "get": {
        "tags": [
          "Example"
        ],
        "summary": "ReadExample",
        "operationId": "V1ExampleValuesGet",
        "consumes": [],
        "produces": [
          "application/json"
        ],
        "parameters": []
      }
    }
```

The pieces that are not working as expected are:
```
        "summary": "ReadExample",
        "operationId": "V1ExampleValuesGet",
```

I would expect `summary` to be `An example endpoint that can be accessed with a GET to v1/example/values\r\nBe default, endpoints allow anonymous callers.` based on the XML documentation and `operationId to be `ReadExample` based on the method name or the specified `SwaggerOperation`.

For reference, here's my registration:
```
            services.ConfigureSwaggerGen(c =>
            {
                c.DocumentFilter<MyCustom.Filters.TrackRoleMetadataDocumentFilter>();
                c.IgnoreObsoleteActions();
                c.IgnoreObsoleteProperties();
                c.DescribeAllEnumsAsStrings();
                c.IncludeXmlComments(string.Format(@"{0}" + options.XmlCommentsPath, AppDomain.CurrentDomain.BaseDirectory));
                c.EnableAnnotations();
            });

            services.AddSwaggerGen(c =>
            {
                var info = new Info
                {
                    Title = options.ServiceTitle,
                    Description = options.ServiceDescription,
                    Version = options.Version
                };
                c.SwaggerDoc(type.ToLowerInvariant(), info);
                c.OperationFilter<ExamplesOperationFilter>();

                var schemaFilterTypes = GetInjectedSchemaFilters(services);
                if (schemaFilterTypes != null)
                {
                    foreach (var schemaFilterType in schemaFilterTypes)
                    {
                        Type sgo = typeof(SwaggerGenOptions);
                        MethodInfo mi = sgo.GetMethod("SchemaFilter");
                        MethodInfo miConstructed = mi.MakeGenericMethod(schemaFilterType);
                        miConstructed.Invoke(c, new object[] { new object[] { } });
                    }
                }
            });
```

**Comment by Blackbaud-ChristiSchneider** [comment]
I also tried `[HttpGet("", Name = "ReadExample")]` and that produces runtime error

```
System.NotSupportedException: Ambiguous HTTP method for action - MyDataService.Controllers.ExampleController.ReadExample (MyDataService). Actions require an explicit HttpMethod binding for Swagger 2.0
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jrodenburg** [comment]
I have this working with as expected with the 3.0 Annotations version.

Here's my controller code (snippets):
`

       [Route("[controller]")]
       [ApiController]
       [Produces("application/json")]
       public class PartnersController  {

       
        [HttpGet]
        [ProducesResponseType(200)]
        [Produces("application/json")]
        **[SwaggerOperation(OperationId = "GetPartners")]**
        public override IActionResult Get()
        {
            .....
        }

`

Here's my Startup.cs code (snippet):

`

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Partner API", Version = "v1" });
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);
                **c.EnableAnnotations();**
            });

`

**Comment by Blackbaud-ChristiSchneider** [comment]
Thanks, that seems to have done the trick!

**Comment by IanMercer** [comment]
Adding a `Name` parameter to `[HttpGet]` fails as @Blackbaud-ChristiSchneider described above, but putting a `Name` on the `Route` attribute seems to work:

        /// <summary>
        /// Get all devices
        /// </summary>
        [Route("devices", Name = "GetAllDevices")]
        [Authorize]
        [HttpGet]
        [Produces(typeof(Device[]))]
        public async Task<IActionResult> GetAllDevices() { ...}
